-- Criminal Empire Online v0.6.5 — Map Shops & Item Availability Expansion

CREATE TABLE IF NOT EXISTS shops (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(120) NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  description TEXT NULL,
  shop_type VARCHAR(80) NOT NULL,
  world_region_id BIGINT UNSIGNED NOT NULL,
  world_location_id BIGINT UNSIGNED NOT NULL,
  owner_npc_id BIGINT UNSIGNED NULL,
  linked_business_id BIGINT UNSIGNED NULL,
  requires_local_presence TINYINT(1) NOT NULL DEFAULT 1,
  can_view_remotely TINYINT(1) NOT NULL DEFAULT 1,
  is_black_market TINYINT(1) NOT NULL DEFAULT 0,
  is_legal TINYINT(1) NOT NULL DEFAULT 1,
  is_known TINYINT(1) NOT NULL DEFAULT 1,
  heat_risk INT NOT NULL DEFAULT 0,
  police_pressure_modifier INT NOT NULL DEFAULT 0,
  min_level INT NOT NULL DEFAULT 1,
  min_reputation INT NOT NULL DEFAULT 0,
  required_contact_trust INT NOT NULL DEFAULT 0,
  buys_categories_json JSON NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  INDEX shops_location_active (world_location_id, is_active),
  INDEX shops_type_known (shop_type, is_known, is_active),
  FOREIGN KEY (world_region_id) REFERENCES world_regions(id) ON DELETE CASCADE,
  FOREIGN KEY (world_location_id) REFERENCES world_locations(id) ON DELETE CASCADE,
  FOREIGN KEY (linked_business_id) REFERENCES businesses(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS shop_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  shop_id BIGINT UNSIGNED NOT NULL,
  item_key VARCHAR(120) NOT NULL,
  asset_type ENUM('item','weapon') NOT NULL DEFAULT 'item',
  item_name VARCHAR(160) NOT NULL,
  item_category VARCHAR(80) NOT NULL,
  description TEXT NULL,
  can_buy TINYINT(1) NOT NULL DEFAULT 1,
  can_sell TINYINT(1) NOT NULL DEFAULT 1,
  buy_price BIGINT UNSIGNED NOT NULL DEFAULT 0,
  sell_price_multiplier DECIMAL(5,2) NOT NULL DEFAULT 0.45,
  stock_quantity INT NULL,
  max_stock INT NULL,
  restock_interval_minutes INT NULL,
  last_restocked_at DATETIME NULL,
  min_level INT NOT NULL DEFAULT 1,
  min_reputation INT NOT NULL DEFAULT 0,
  heat_risk INT NOT NULL DEFAULT 0,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  availability_status VARCHAR(80) NOT NULL DEFAULT 'legal',
  disabled_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY unique_shop_item_key (shop_id, item_key),
  INDEX shop_items_status (availability_status, is_enabled),
  FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_transactions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  shop_id BIGINT UNSIGNED NOT NULL,
  item_key VARCHAR(120) NOT NULL,
  asset_type ENUM('item','weapon') NOT NULL DEFAULT 'item',
  action_type ENUM('buy','sell') NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  unit_price BIGINT UNSIGNED NOT NULL,
  total_price BIGINT UNSIGNED NOT NULL,
  source_inventory_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  INDEX shop_transactions_user_created (user_id, created_at),
  INDEX shop_transactions_shop_created (shop_id, created_at),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE CASCADE
);
