UPDATE weapons
SET
  equipment_slot = 'sidearm',
  effects = JSON_OBJECT(
    'armed_role_bonus', 10,
    'intimidation_bonus', 8,
    'heat_modifier', 3,
    'failure_severity_modifier', 4
  ),
  base_durability = 100,
  storage_units = 4,
  illegal = 1
WHERE class = 'pistol';

UPDATE weapons
SET
  equipment_slot = 'weapon',
  effects = JSON_OBJECT(
    'armed_role_bonus', 16,
    'intimidation_bonus', 12,
    'heat_modifier', 6,
    'failure_severity_modifier', 7
  ),
  base_durability = 100,
  storage_units = 8,
  illegal = 1
WHERE class IN ('shotgun', 'smg', 'assault_rifle');

INSERT INTO item_definitions (
  code,
  name,
  category,
  equipment_slot,
  description,
  price,
  storage_units,
  max_durability,
  illegal,
  stackable,
  effects,
  requirements,
  active,
  created_at,
  updated_at
) VALUES
(
  'cheap_knife',
  'Cheap Knife',
  'melee_weapon',
  'melee_weapon',
  'A concealable street weapon. Useful for intimidation but risky if exposed.',
  80,
  1,
  100,
  1,
  1,
  JSON_OBJECT('intimidation_bonus', 4, 'armed_role_bonus', 3, 'heat_modifier', 1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'crowbar',
  'Crowbar',
  'tool',
  'tool',
  'Improves forced entry, but creates noise and evidence.',
  95,
  2,
  100,
  0,
  1,
  JSON_OBJECT('forced_entry_bonus', 12, 'burglary_bonus', 7, 'heat_modifier', 1, 'evidence_modifier', 2),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'lockpick_set',
  'Lockpick Set',
  'tool',
  'tool',
  'Supports quieter entry when used by a skilled infiltrator.',
  140,
  1,
  100,
  1,
  1,
  JSON_OBJECT('stealth_entry_bonus', 12, 'burglary_bonus', 8, 'heat_modifier', -1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'work_gloves',
  'Work Gloves',
  'clothing',
  'clothing',
  'Reduces evidence left during theft and burglary jobs.',
  25,
  1,
  80,
  0,
  1,
  JSON_OBJECT('evidence_modifier', -8, 'heat_modifier', -1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'dark_clothing',
  'Dark Clothing',
  'clothing',
  'Basic low-profile clothing for night work.',
  65,
  1,
  80,
  0,
  1,
  JSON_OBJECT('stealth_bonus', 5, 'heat_modifier', -1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'basic_vest',
  'Basic Protective Vest',
  'armor',
  'armor',
  'Provides modest protection during dangerous jobs.',
  450,
  3,
  120,
  0,
  1,
  JSON_OBJECT('injury_modifier', -10, 'combat_bonus', 3),
  JSON_OBJECT('min_reputation', 5),
  1,
  NOW(),
  NOW()
),
(
  'duffel_bag',
  'Duffel Bag',
  'utility',
  'utility',
  'Increases the amount of physical loot the crew can carry.',
  75,
  1,
  100,
  0,
  1,
  JSON_OBJECT('loot_capacity_bonus', 20, 'reward_modifier', 0.05),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'burner_phone',
  'Burner Phone',
  'utility',
  'utility',
  'Reduces coordination mistakes and lowers communication evidence.',
  110,
  1,
  100,
  1,
  1,
  JSON_OBJECT('planning_bonus', 5, 'evidence_modifier', -3),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'first_aid_kit',
  'First-Aid Kit',
  'utility',
  'utility',
  'Reduces injury severity after a difficult operation.',
  90,
  1,
  1,
  0,
  1,
  JSON_OBJECT('injury_modifier', -8),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'basic_surveillance_kit',
  'Basic Surveillance Kit',
  'tool',
  'tool',
  'A simple observation kit used during scouting preparation.',
  260,
  2,
  100,
  0,
  1,
  JSON_OBJECT('scouting_bonus', 10, 'planning_bonus', 4),
  JSON_OBJECT('min_reputation', 3),
  1,
  NOW(),
  NOW()
),
(
  'abstract_grow_kit',
  'Compact Grow Kit',
  'production_supply',
  NULL,
  'An abstract game resource used by the fictional warehouse production operation.',
  650,
  10,
  1,
  1,
  1,
  JSON_OBJECT('production_bonus', 12),
  JSON_OBJECT('requires_warehouse', true),
  1,
  NOW(),
  NOW()
),
(
  'stolen_electronics',
  'Stolen Electronics',
  'stolen_good',
  NULL,
  'Unfenced electronics taken during a job.',
  0,
  4,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 300),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'car_lamps',
  'Stolen Car Lamps',
  'vehicle_part',
  NULL,
  'Vehicle parts that can be stored for a later NPC buyer.',
  0,
  2,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 110),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'catalytic_converter',
  'Catalytic Converter',
  'vehicle_part',
  NULL,
  'A valuable but high-risk stolen vehicle part.',
  0,
  4,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 420),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  category = VALUES(category),
  equipment_slot = VALUES(equipment_slot),
  description = VALUES(description),
  price = VALUES(price),
  storage_units = VALUES(storage_units),
  max_durability = VALUES(max_durability),
  illegal = VALUES(illegal),
  effects = VALUES(effects),
  requirements = VALUES(requirements),
  active = VALUES(active),
  updated_at = NOW();

INSERT INTO npcs (
  id,
  first_name,
  last_name,
  nickname,
  age,
  gender,
  biography,
  background,
  occupation,
  role,
  home_territory_id,
  personal_cash,
  income_weekly,
  expenses_weekly,
  wealth_class,
  reputation,
  criminal_reputation,
  health,
  max_health,
  morale,
  loyalty,
  status,
  created_at,
  updated_at
) VALUES
(
  1201,
  'Darren',
  'Cole',
  'Switch',
  34,
  'male',
  'Darren “Switch” Cole grew up around the East Yard garages. He worked as a mechanic before doing vehicle jobs for the Red Knives. After a dispute over unpaid money, he left the gang and began arranging small work for independent crews.',
  'Former Red Knives mechanic',
  'Back-alley mechanic',
  'criminal_contact',
  (SELECT id FROM territories WHERE name = 'Industrial Zone'),
  6200,
  900,
  700,
  'working',
  30,
  58,
  100,
  100,
  63,
  47,
  'active',
  NOW(),
  NOW()
),
(
  1202,
  'Elena',
  'Voss',
  'Ledger',
  41,
  'female',
  'Elena keeps careful notes, knows which shops carry weak insurance, and pays reliably when a crew follows instructions.',
  'Former insurance clerk',
  'Fence and information broker',
  'criminal_contact',
  (SELECT id FROM territories WHERE name = 'Old Town'),
  9800,
  1300,
  850,
  'working',
  42,
  65,
  100,
  100,
  70,
  55,
  'active',
  NOW(),
  NOW()
),
(
  1203,
  'Malik',
  'Stone',
  'Quiet Man',
  46,
  'male',
  'Malik arranges debt work and knows when a warning is more useful than violence.',
  'Former nightclub security manager',
  'Debt collector',
  'criminal_contact',
  (SELECT id FROM territories WHERE name = 'Downtown'),
  11000,
  1500,
  1000,
  'working',
  50,
  70,
  100,
  100,
  58,
  48,
  'active',
  NOW(),
  NOW()
),
(
  1204,
  'Ruth',
  'Meyer',
  'Keys',
  55,
  'female',
  'Ruth manages neglected industrial properties for owners who prefer cash and few questions.',
  'Commercial property caretaker',
  'Property broker',
  'property_broker',
  (SELECT id FROM territories WHERE name = 'Industrial Zone'),
  23000,
  1800,
  1100,
  'comfortable',
  35,
  20,
  100,
  100,
  72,
  62,
  'active',
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  biography = VALUES(biography),
  background = VALUES(background),
  occupation = VALUES(occupation),
  role = VALUES(role),
  updated_at = NOW();

INSERT INTO npc_contacts (
  npc_id,
  contact_type,
  job_categories,
  payment_reliability,
  criminal_connections,
  active,
  created_at,
  updated_at
) VALUES
(1201, 'mechanic', JSON_ARRAY('vehicle_crime', 'theft', 'delivery'), 78, 68, 1, NOW(), NOW()),
(1202, 'fence', JSON_ARRAY('theft', 'burglary', 'smuggling'), 90, 76, 1, NOW(), NOW()),
(1203, 'collector', JSON_ARRAY('collection', 'intimidation', 'robbery'), 82, 72, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  contact_type = VALUES(contact_type),
  job_categories = VALUES(job_categories),
  payment_reliability = VALUES(payment_reliability),
  criminal_connections = VALUES(criminal_connections),
  active = 1,
  updated_at = NOW();

INSERT INTO dirty_job_templates (
  code,
  category,
  tier,
  title,
  short_description,
  introduction,
  briefing,
  preparation_text,
  execution_text,
  success_text,
  partial_success_text,
  failure_text,
  critical_failure_text,
  duration_seconds,
  energy_cost,
  reward_min,
  reward_max,
  dirty_money_percent,
  experience_gain,
  reputation_gain,
  base_success_rate,
  difficulty,
  heat_min,
  heat_max,
  min_level,
  min_reputation,
  min_crew_size,
  required_roles,
  required_items,
  preparation_options,
  event_definition,
  reward_definition,
  requires_warehouse,
  active,
  created_at,
  updated_at
) VALUES
(
  'steal_car_lamps',
  'vehicle_crime',
  1,
  'Lights Out',
  'Remove valuable lamps from a parked car before patrols circle back.',
  'Switch knows a buyer who needs matching lamps tonight.',
  'The target is parked behind an aging apartment block. The job is quiet, but residents sometimes watch the lot.',
  'A quick scout or work gloves can reduce evidence and surprise.',
  'The crew moves between parked cars while one person watches the street.',
  'The lamps come free cleanly and the buyer accepts the lot.',
  'Only part of the set survives, but there is still something to sell.',
  'A resident switches on a light and the crew abandons the work.',
  'A patrol turns into the lot while tools are still in hand.',
  90,
  7,
  70,
  150,
  35,
  10,
  2,
  72,
  18,
  1,
  5,
  1,
  0,
  0,
  JSON_ARRAY(),
  JSON_ARRAY(),
  JSON_ARRAY(
    JSON_OBJECT('code', 'scout_target', 'name', 'Scout the lot', 'cash_cost', 0, 'energy_cost', 2, 'success_bonus', 7, 'heat_modifier', -1),
    JSON_OBJECT('code', 'buy_schedule', 'name', 'Buy patrol timing', 'cash_cost', 35, 'energy_cost', 0, 'success_bonus', 8, 'heat_modifier', -2)
  ),
  JSON_OBJECT(
    'prompt', 'A resident enters the lot earlier than expected. What should the crew do?',
    'options', JSON_ARRAY(
      JSON_OBJECT('code', 'wait_in_shadows', 'label', 'Wait in the shadows', 'success_bonus', 4, 'heat_modifier', -1),
      JSON_OBJECT('code', 'finish_fast', 'label', 'Finish quickly', 'success_bonus', 1, 'reward_modifier', 1.10, 'heat_modifier', 2)
    )
  ),
  JSON_OBJECT('item_code', 'car_lamps', 'quantity_min', 1, 'quantity_max', 2, 'vehicle_chance', 0),
  0,
  1,
  NOW(),
  NOW()
),
(
  'shoplift_electronics',
  'theft',
  1,
  'Five-Minute Window',
  'Take small electronics during a busy shift change.',
  'Ledger has a buyer for boxed electronics with intact serial labels.',
  'The store is crowded enough to hide movement, but cameras cover the main exit.',
  'Study camera angles, arrange a distraction, or carry a larger bag.',
  'The crew enters separately and converges near the stock shelves.',
  'The goods leave unnoticed and the contact confirms the pickup.',
  'Some boxes are abandoned, but the crew keeps a smaller haul.',
  'Security notices the pattern and closes the exit.',
  'The crew is identified on camera and must escape with nothing.',
  120,
  8,
  90,
  220,
  25,
  12,
  2,
  68,
  22,
  2,
  7,
  1,
  0,
  0,
  JSON_ARRAY(),
  JSON_ARRAY(),
  JSON_ARRAY(
    JSON_OBJECT('code', 'study_cameras', 'name', 'Study camera coverage', 'cash_cost', 0, 'energy_cost', 3, 'success_bonus', 9, 'heat_modifier', -1),
    JSON_OBJECT('code', 'pay_distraction', 'name', 'Pay for a distraction', 'cash_cost', 45, 'energy_cost', 0, 'success_bonus', 10, 'heat_modifier', 0)
  ),
  NULL,
  JSON_OBJECT('item_code', 'stolen_electronics', 'quantity_min', 1, 'quantity_max', 2),
  0,
  1,
  NOW(),
  NOW()
),
(
  'apartment_burglary',
  'burglary',
  2,
  'Empty Apartment',
  'Enter a small apartment while its tenant works a late shift.',
  'Ledger has matched a buyer with a poorly secured apartment.',
  'The building has a rear stairwell and an old lock. Noise will draw attention from neighbors.',
  'Scout the building, buy a copy of the shift schedule, or assign a lookout.',
  'An infiltrator works the entrance while the lookout watches the stairwell.',
  'The crew clears the marked valuables before anyone returns.',
  'The crew leaves early with only part of the planned haul.',
  'The lock refuses to cooperate and neighbors begin moving upstairs.',
  'The tenant returns unexpectedly while the crew is inside.',
  240,
  12,
  180,
  520,
  55,
  24,
  5,
  60,
  34,
  4,
  12,
  1,
  5,
  1,
  JSON_ARRAY('infiltrator'),
  JSON_ARRAY(),
  JSON_ARRAY(
    JSON_OBJECT('code', 'scout_building', 'name', 'Scout the stairwell', 'cash_cost', 0, 'energy_cost', 4, 'success_bonus', 8, 'heat_modifier', -1),
    JSON_OBJECT('code', 'buy_shift_schedule', 'name', 'Buy the tenant schedule', 'cash_cost', 75, 'energy_cost', 0, 'success_bonus', 10, 'heat_modifier', -2)
  ),
  JSON_OBJECT(
    'prompt', 'A neighbor starts walking up the rear stairs.',
    'options', JSON_ARRAY(
      JSON_OBJECT('code', 'abort_room', 'label', 'Leave one room untouched and exit', 'success_bonus', 5, 'reward_modifier', 0.80, 'heat_modifier', -2),
      JSON_OBJECT('code', 'hide_and_continue', 'label', 'Hide and continue', 'success_bonus', -2, 'reward_modifier', 1.15, 'heat_modifier', 2)
    )
  ),
  JSON_OBJECT('item_code', 'stolen_electronics', 'quantity_min', 1, 'quantity_max', 3),
  0,
  1,
  NOW(),
  NOW()
),
(
  'garage_parts_raid',
  'burglary',
  2,
  'After-Hours Garage',
  'Raid a mechanic garage for tools and vehicle parts.',
  'Switch knows a garage owner who stores valuable parts without proper alarms.',
  'The side door is reinforced and the yard has one unreliable camera.',
  'Scout the yard, prepare a quieter entry method, or arrange transport.',
  'The crew enters through the side yard and moves marked crates.',
  'The crates reach the buyer before the owner notices the loss.',
  'Only the lightest parts are moved before the alarm begins.',
  'The crew leaves empty-handed after triggering the side-door alarm.',
  'The owner arrives armed and the crew scatters under pressure.',
  300,
  14,
  260,
  700,
  60,
  30,
  7,
  57,
  40,
  5,
  15,
  2,
  10,
  2,
  JSON_ARRAY('infiltrator', 'lookout'),
  JSON_ARRAY(),
  JSON_ARRAY(
    JSON_OBJECT('code', 'disable_camera', 'name', 'Map the old camera', 'cash_cost', 55, 'energy_cost', 2, 'success_bonus', 9, 'heat_modifier', -2),
    JSON_OBJECT('code', 'rent_transport', 'name', 'Arrange anonymous transport', 'cash_cost', 120, 'energy_cost', 0, 'success_bonus', 5, 'reward_modifier', 1.10, 'heat_modifier', -1)
  ),
  NULL,
  JSON_OBJECT('item_code', 'catalytic_converter', 'quantity_min', 1, 'quantity_max', 2),
  0,
  1,
  NOW(),
  NOW()
),
(
  'steal_delivery_van',
  'vehicle_crime',
  3,
  'Borrowed Van',
  'Take a low-value delivery van and move it to an NPC buyer.',
  'Switch has a buyer who needs a common delivery van with minimal visible damage.',
  'The van follows the same route each evening. The driver takes a short break near the Harbor.',
  'Study the route, arrange a driver, and prepare a quiet entry tool.',
  'The crew approaches during the driver’s break and moves the van through side streets.',
  'The van reaches the buyer with its value mostly intact.',
  'The buyer accepts the van at a reduced price because of damage.',
  'The driver returns early and the crew abandons the attempt.',
  'A patrol recognizes the stolen van and blocks the exit route.',
  420,
  18,
  650,
  1500,
  70,
  48,
  12,
  52,
  50,
  8,
  22,
  2,
  25,
  2,
  JSON_ARRAY('driver', 'lookout'),
  JSON_ARRAY(),
  JSON_ARRAY(
    JSON_OBJECT('code', 'study_route', 'name', 'Study the route', 'cash_cost', 0, 'energy_cost', 5, 'success_bonus', 10, 'heat_modifier', -1),
    JSON_OBJECT('code', 'buy_spare_key', 'name', 'Buy a copied key', 'cash_cost', 220, 'energy_cost', 0, 'success_bonus', 13, 'heat_modifier', -2)
  ),
  JSON_OBJECT(
    'prompt', 'The usual side street is blocked by road work.',
    'options', JSON_ARRAY(
      JSON_OBJECT('code', 'slow_detour', 'label', 'Take the slow industrial detour', 'success_bonus', 4, 'reward_modifier', 0.95, 'heat_modifier', -1),
      JSON_OBJECT('code', 'busy_road', 'label', 'Use the busy main road', 'success_bonus', 1, 'reward_modifier', 1.05, 'heat_modifier', 3)
    )
  ),
  JSON_OBJECT('vehicle_name', 'Stolen Delivery Van', 'vehicle_type', 'van', 'condition_min', 45, 'condition_max', 75, 'estimated_value', 1800),
  0,
  1,
  NOW(),
  NOW()
),
(
  'collect_rival_payment',
  'collection',
  2,
  'Late Payment',
  'Collect a delayed payment without turning the district against you.',
  'Quiet Man needs a dependable crew to recover a small debt.',
  'The debtor runs a small back room and is more stubborn than dangerous.',
  'Learn who is present, assign an enforcer, or pay for private access.',
  'The crew enters calmly and presents the debt one final time.',
  'The debtor pays and the contact approves of the controlled approach.',
  'The debtor pays only part of the balance after a tense argument.',
  'The debtor refuses and draws attention from nearby businesses.',
  'The confrontation escalates and police are called immediately.',
  210,
  11,
  170,
  480,
  80,
  22,
  5,
  62,
  32,
  3,
  11,
  1,
  5,
  1,
  JSON_ARRAY('enforcer'),
  JSON_ARRAY(),
  JSON_ARRAY(
    JSON_OBJECT('code', 'learn_routine', 'name', 'Learn the debtor routine', 'cash_cost', 35, 'energy_cost', 1, 'success_bonus', 7, 'heat_modifier', -1),
    JSON_OBJECT('code', 'private_access', 'name', 'Pay for private access', 'cash_cost', 90, 'energy_cost', 0, 'success_bonus', 9, 'heat_modifier', -2)
  ),
  NULL,
  JSON_OBJECT(),
  0,
  1,
  NOW(),
  NOW()
),
(
  'warehouse_grow_cycle',
  'production',
  4,
  'Green Room',
  'Run an abstract fictional cannabis production cycle inside a secured warehouse.',
  'A contact can supply a compact fictional production kit and a buyer for the finished product.',
  'This operation is represented through abstract game resources, crew management, risk, and time. It does not model real-world cultivation procedures.',
  'Secure the warehouse, assign a disciplined grow operator, and reduce visibility.',
  'The assigned operator maintains the abstract production cycle while the crew handles interruptions.',
  'The cycle finishes and packaged cannabis is moved into warehouse storage.',
  'Only part of the planned output is usable after a maintenance problem.',
  'The cycle fails and the supplies are lost.',
  'A complaint brings attention to the property and forces an emergency shutdown.',
  900,
  20,
  900,
  2100,
  100,
  70,
  18,
  58,
  55,
  10,
  28,
  3,
  45,
  1,
  JSON_ARRAY('grow_operator'),
  JSON_ARRAY('abstract_grow_kit'),
  JSON_ARRAY(
    JSON_OBJECT('code', 'security_check', 'name', 'Inspect warehouse security', 'cash_cost', 0, 'energy_cost', 5, 'success_bonus', 8, 'heat_modifier', -2),
    JSON_OBJECT('code', 'quiet_utilities', 'name', 'Pay for discreet utility handling', 'cash_cost', 280, 'energy_cost', 0, 'success_bonus', 10, 'heat_modifier', -3)
  ),
  JSON_OBJECT(
    'prompt', 'A nearby tenant reports unusual activity around the building.',
    'options', JSON_ARRAY(
      JSON_OBJECT('code', 'pause_cycle', 'label', 'Pause and lower activity', 'success_bonus', 5, 'reward_modifier', 0.80, 'heat_modifier', -4),
      JSON_OBJECT('code', 'continue_quietly', 'label', 'Continue with tighter discipline', 'success_bonus', 1, 'reward_modifier', 1.00, 'heat_modifier', 1)
    )
  ),
  JSON_OBJECT('drug_id', 1, 'quantity_min', 8, 'quantity_max', 22, 'warehouse_only', true),
  1,
  1,
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  category = VALUES(category),
  tier = VALUES(tier),
  title = VALUES(title),
  short_description = VALUES(short_description),
  introduction = VALUES(introduction),
  briefing = VALUES(briefing),
  preparation_text = VALUES(preparation_text),
  execution_text = VALUES(execution_text),
  success_text = VALUES(success_text),
  partial_success_text = VALUES(partial_success_text),
  failure_text = VALUES(failure_text),
  critical_failure_text = VALUES(critical_failure_text),
  duration_seconds = VALUES(duration_seconds),
  energy_cost = VALUES(energy_cost),
  reward_min = VALUES(reward_min),
  reward_max = VALUES(reward_max),
  dirty_money_percent = VALUES(dirty_money_percent),
  experience_gain = VALUES(experience_gain),
  reputation_gain = VALUES(reputation_gain),
  base_success_rate = VALUES(base_success_rate),
  difficulty = VALUES(difficulty),
  heat_min = VALUES(heat_min),
  heat_max = VALUES(heat_max),
  min_level = VALUES(min_level),
  min_reputation = VALUES(min_reputation),
  min_crew_size = VALUES(min_crew_size),
  required_roles = VALUES(required_roles),
  required_items = VALUES(required_items),
  preparation_options = VALUES(preparation_options),
  event_definition = VALUES(event_definition),
  reward_definition = VALUES(reward_definition),
  requires_warehouse = VALUES(requires_warehouse),
  active = VALUES(active),
  updated_at = NOW();

INSERT INTO building_types (
  code,
  name,
  description,
  created_at,
  updated_at
) VALUES (
  'warehouse',
  'Warehouse',
  'A secure base for storing contraband, equipment, stolen goods, vehicle parts, and vehicles.',
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  updated_at = NOW();

INSERT INTO property_listings (
  building_type_id,
  seller_npc_id,
  territory_id,
  name,
  description,
  purchase_price,
  storage_capacity,
  vehicle_capacity,
  security_rating,
  condition_rating,
  weekly_operating_cost,
  heat_visibility,
  status,
  repeatable,
  created_at,
  updated_at
)
SELECT
  building_types.id,
  1204,
  territories.id,
  'Old Freight Annex',
  'A neglected freight annex with one vehicle bay, basic locks, and enough room for a young crew.',
  7500,
  180,
  1,
  28,
  52,
  120,
  18,
  'available',
  1,
  NOW(),
  NOW()
FROM building_types
JOIN territories ON territories.name = 'Industrial Zone'
WHERE building_types.code = 'warehouse'
  AND NOT EXISTS (
    SELECT 1
    FROM property_listings
    WHERE name = 'Old Freight Annex'
  );

INSERT INTO property_listings (
  building_type_id,
  seller_npc_id,
  territory_id,
  name,
  description,
  purchase_price,
  storage_capacity,
  vehicle_capacity,
  security_rating,
  condition_rating,
  weekly_operating_cost,
  heat_visibility,
  status,
  repeatable,
  created_at,
  updated_at
)
SELECT
  building_types.id,
  1204,
  territories.id,
  'Riverside Lockup',
  'A cleaner lockup with better doors and room for two vehicles.',
  12500,
  280,
  2,
  42,
  68,
  190,
  15,
  'available',
  1,
  NOW(),
  NOW()
FROM building_types
JOIN territories ON territories.name = 'Harbor'
WHERE building_types.code = 'warehouse'
  AND NOT EXISTS (
    SELECT 1
    FROM property_listings
    WHERE name = 'Riverside Lockup'
  );

INSERT INTO building_upgrades (
  code,
  name,
  description,
  price,
  effects,
  created_at,
  updated_at
) VALUES
(
  'stronger_locks',
  'Stronger Locks',
  'Improves warehouse security and slightly lowers theft risk.',
  850,
  JSON_OBJECT('security_bonus', 10),
  NOW(),
  NOW()
),
(
  'basic_alarm',
  'Basic Alarm',
  'Improves detection of unauthorized entry.',
  1400,
  JSON_OBJECT('security_bonus', 15, 'heat_visibility_modifier', 1),
  NOW(),
  NOW()
),
(
  'hidden_compartment',
  'Hidden Compartment',
  'Adds concealed storage and lowers discovery risk.',
  2200,
  JSON_OBJECT('storage_bonus', 25, 'heat_visibility_modifier', -4),
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  price = VALUES(price),
  effects = VALUES(effects),
  updated_at = NOW();
