UPDATE item_definitions SET name = 'First Aid Kit', description = 'A red field first aid kit for patching up crew after risky work.', updated_at = NOW() WHERE code = 'first_aid_kit';

UPDATE item_definitions SET name = 'Dark Hoodie', updated_at = NOW() WHERE code = 'dark_clothing';

UPDATE item_definitions SET name = 'Protective Vest', updated_at = NOW() WHERE code = 'basic_vest';

UPDATE item_definitions SET name = 'Messenger Bag', updated_at = NOW() WHERE code = 'duffel_bag';

UPDATE item_definitions SET name = 'Smartphone', updated_at = NOW() WHERE code = 'burner_phone';

INSERT INTO item_definitions (
  code,
  name,
  category,
  equipment_slot,
  description,
  price,
  storage_units,
  max_durability,
  illegal,
  stackable,
  effects,
  requirements,
  active,
  created_at,
  updated_at
) VALUES

(
  'bandages',
  'Bandages',
  'utility',
  'utility',
  'Basic field bandages that help the crew recover minor wounds after rough work.',
  20,
  1,
  1,
  0,
  1,
  JSON_OBJECT('injury_modifier', -4),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'smartphone',
  'Smartphone',
  'utility',
  'utility',
  'A clean modern phone useful for planning, navigation, and fast communication.',
  180,
  1,
  100,
  0,
  1,
  JSON_OBJECT('planning_bonus', 4, 'communication_bonus', 4),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'notebook',
  'Notebook',
  'utility',
  'utility',
  'Used to keep notes, schedules, and target details organised.',
  18,
  1,
  100,
  0,
  1,
  JSON_OBJECT('planning_bonus', 2),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'water_bottle',
  'Water Bottle',
  'utility',
  'utility',
  'A simple hydration item for long shifts and stakeouts.',
  10,
  1,
  1,
  0,
  1,
  JSON_OBJECT('endurance_bonus', 1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'battery_pack',
  'Battery Pack',
  'utility',
  'utility',
  'Keeps electronics powered during longer operations.',
  45,
  1,
  100,
  0,
  1,
  JSON_OBJECT('planning_bonus', 1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'toolbox',
  'Toolbox',
  'tool',
  'tool',
  'A general-purpose tool case for vehicle jobs and maintenance-heavy work.',
  140,
  2,
  100,
  0,
  1,
  JSON_OBJECT('vehicle_job_bonus', 6, 'forced_entry_bonus', 4),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'cleaning_kit',
  'Cleaning Kit',
  'tool',
  'tool',
  'Helps reduce evidence and clean up after a messy operation.',
  55,
  1,
  100,
  0,
  1,
  JSON_OBJECT('evidence_modifier', -6),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'leather_gloves',
  'Leather Gloves',
  'clothing',
  'clothing',
  'Tough gloves that improve grip and reduce trace evidence.',
  40,
  1,
  80,
  0,
  1,
  JSON_OBJECT('evidence_modifier', -4, 'stealth_bonus', 1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'dark_hoodie',
  'Dark Hoodie',
  'clothing',
  'clothing',
  'A low-profile hoodie suited for quiet night work.',
  70,
  1,
  90,
  0,
  1,
  JSON_OBJECT('stealth_bonus', 5, 'heat_modifier', -1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'dark_jacket',
  'Dark Jacket',
  'clothing',
  'clothing',
  'A durable dark jacket that helps blend into city streets.',
  95,
  1,
  100,
  0,
  1,
  JSON_OBJECT('stealth_bonus', 3, 'injury_modifier', -2),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'heavy_boots',
  'Heavy Boots',
  'clothing',
  'clothing',
  'Solid boots for harsh environments and rough terrain.',
  85,
  1,
  100,
  0,
  1,
  JSON_OBJECT('endurance_bonus', 2),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'work_boots',
  'Work Boots',
  'clothing',
  'clothing',
  'Reliable work boots for warehouse runs and industrial jobs.',
  75,
  1,
  100,
  0,
  1,
  JSON_OBJECT('endurance_bonus', 1, 'vehicle_job_bonus', 2),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'protective_vest',
  'Protective Vest',
  'armor',
  'armor',
  'A practical ballistic vest that lowers injury severity.',
  520,
  3,
  120,
  0,
  1,
  JSON_OBJECT('injury_modifier', -12, 'combat_bonus', 3),
  JSON_OBJECT('min_reputation', 5),
  1,
  NOW(),
  NOW()
),
(
  'raincoat',
  'Raincoat',
  'clothing',
  'clothing',
  'Useful during wet operations and poor-visibility weather.',
  50,
  1,
  90,
  0,
  1,
  JSON_OBJECT('heat_modifier', -1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'beanie',
  'Beanie',
  'clothing',
  'clothing',
  'A simple cap that helps a crew member keep a low profile.',
  18,
  1,
  60,
  0,
  1,
  JSON_OBJECT('stealth_bonus', 1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'cap',
  'Cap',
  'clothing',
  'clothing',
  'Casual headwear with a forgettable street look.',
  18,
  1,
  60,
  0,
  1,
  JSON_OBJECT('stealth_bonus', 1),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'backpack',
  'Backpack',
  'utility',
  'utility',
  'Useful for carrying gear or loot without drawing attention.',
  60,
  1,
  100,
  0,
  1,
  JSON_OBJECT('loot_capacity_bonus', 12),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'messenger_bag',
  'Messenger Bag',
  'utility',
  'utility',
  'A compact bag suited to errands, documents, or smaller valuables.',
  58,
  1,
  100,
  0,
  1,
  JSON_OBJECT('loot_capacity_bonus', 8),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'sedan',
  'Sedan',
  'general',
  NULL,
  'A standard civilian sedan that can be stored or traded as transport.',
  1800,
  8,
  100,
  1,
  0,
  JSON_OBJECT('transport_value', 18),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'getaway_car',
  'Getaway Car',
  'general',
  NULL,
  'A tuned street car prepared for a fast exit.',
  3600,
  10,
  100,
  1,
  0,
  JSON_OBJECT('escape_bonus', 10, 'vehicle_job_bonus', 8),
  JSON_OBJECT('min_reputation', 8),
  1,
  NOW(),
  NOW()
),
(
  'van',
  'Van',
  'general',
  NULL,
  'A basic van with extra cargo room.',
  2200,
  12,
  100,
  1,
  0,
  JSON_OBJECT('loot_capacity_bonus', 18, 'transport_value', 20),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'delivery_van',
  'Delivery Van',
  'general',
  NULL,
  'A larger van useful for transport and cover during cargo jobs.',
  2800,
  14,
  100,
  1,
  0,
  JSON_OBJECT('loot_capacity_bonus', 24, 'vehicle_job_bonus', 6),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'motorcycle',
  'Motorcycle',
  'general',
  NULL,
  'A quick two-wheel vehicle for short-distance movement and scouting.',
  1400,
  6,
  100,
  1,
  0,
  JSON_OBJECT('escape_bonus', 6, 'scouting_bonus', 3),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'truck',
  'Truck',
  'general',
  NULL,
  'Heavy transport suited for larger loads.',
  4200,
  18,
  100,
  1,
  0,
  JSON_OBJECT('loot_capacity_bonus', 32, 'transport_value', 32),
  JSON_OBJECT('min_reputation', 10),
  1,
  NOW(),
  NOW()
),
(
  'boat',
  'Boat',
  'general',
  NULL,
  'A watercraft for smuggling or waterfront operations.',
  5000,
  20,
  100,
  1,
  0,
  JSON_OBJECT('smuggling_bonus', 10),
  JSON_OBJECT('min_reputation', 12),
  1,
  NOW(),
  NOW()
),
(
  'car_key',
  'Car Key',
  'utility',
  'utility',
  'A key for a vehicle stash, drop car, or hot getaway.',
  40,
  1,
  1,
  1,
  1,
  JSON_OBJECT('vehicle_job_bonus', 2),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'garage_key',
  'Garage Key',
  'utility',
  'utility',
  'Grants access to a garage, unit, or temporary storage site.',
  45,
  1,
  1,
  1,
  1,
  JSON_OBJECT('storage_access_bonus', 2),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'fuel_can',
  'Fuel Can',
  'utility',
  'utility',
  'Emergency fuel for vehicles or generators.',
  28,
  1,
  1,
  0,
  1,
  JSON_OBJECT('vehicle_job_bonus', 2),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'spare_plates',
  'Spare Plates',
  'vehicle_part',
  NULL,
  'Unregistered or spare plates that help obscure a vehicle identity.',
  95,
  1,
  1,
  1,
  1,
  JSON_OBJECT('heat_modifier', -2, 'vehicle_job_bonus', 4),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'atv',
  'ATV',
  'general',
  NULL,
  'A rugged all-terrain vehicle for rough routes and hidden access paths.',
  2600,
  10,
  100,
  1,
  0,
  JSON_OBJECT('escape_bonus', 5, 'scouting_bonus', 4),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'cash_bundle',
  'Cash Bundle',
  'stolen_good',
  NULL,
  'Loose cash packaged for transport or hiding.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 120),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'bank_card',
  'Bank Card',
  'stolen_good',
  NULL,
  'A stolen or cloned bank card.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 140),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'gold_watch',
  'Gold Watch',
  'stolen_good',
  NULL,
  'A compact luxury item that sells easily on the street.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 260),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'gold_bar',
  'Gold Bar',
  'stolen_good',
  NULL,
  'High-value metal that is heavy, risky, and worth protecting.',
  0,
  4,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 1200),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'jewelry',
  'Jewelry',
  'stolen_good',
  NULL,
  'Mixed pieces of valuable jewelry.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 420),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'diamond_ring',
  'Diamond Ring',
  'stolen_good',
  NULL,
  'A single standout ring with strong resale value.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 520),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'safe_box',
  'Safe Box',
  'stolen_good',
  NULL,
  'A lockbox containing unknown goods or sensitive records.',
  0,
  4,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 340),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'ledger_book',
  'Ledger Book',
  'stolen_good',
  NULL,
  'Physical records that may contain leverage or blackmail value.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 180),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'contract',
  'Contract',
  'stolen_good',
  NULL,
  'Sensitive paper documents that can be sold or used as leverage.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 150),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'luxury_bag',
  'Luxury Bag',
  'stolen_good',
  NULL,
  'A branded luxury carry bag with resale value.',
  0,
  2,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 360),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'stack_of_coins',
  'Stack of Coins',
  'stolen_good',
  NULL,
  'Collectible coins that can be fenced to specialty buyers.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 230),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'necklace',
  'Necklace',
  'stolen_good',
  NULL,
  'A necklace that can be sold through fences or pawn channels.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 310),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'sealed_package',
  'Sealed Package',
  'production_supply',
  NULL,
  'A suspicious sealed package ready for a drop or exchange.',
  0,
  3,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 180),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'contraband_crate',
  'Contraband Crate',
  'production_supply',
  NULL,
  'Bulk contraband stored in a reinforced crate.',
  0,
  8,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 750),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'wrapped_brick',
  'Wrapped Brick',
  'production_supply',
  NULL,
  'A wrapped parcel of illicit material.',
  0,
  4,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 300),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'powder_packet',
  'Powder Packet',
  'production_supply',
  NULL,
  'A small packet of powder contraband.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 95),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'crystal_bag',
  'Crystal Bag',
  'production_supply',
  NULL,
  'A bag of crystal product meant for black-market sale.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 110),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
),
(
  'syringe_case',
  'Syringe Case',
  'production_supply',
  NULL,
  'A kit associated with high-risk narcotics handling.',
  0,
  1,
  1,
  1,
  1,
  JSON_OBJECT('fence_value', 85),
  JSON_OBJECT(),
  1,
  NOW(),
  NOW()
)

ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  category = VALUES(category),
  equipment_slot = VALUES(equipment_slot),
  description = VALUES(description),
  price = VALUES(price),
  storage_units = VALUES(storage_units),
  max_durability = VALUES(max_durability),
  illegal = VALUES(illegal),
  stackable = VALUES(stackable),
  effects = VALUES(effects),
  requirements = VALUES(requirements),
  active = VALUES(active),
  updated_at = NOW();
