-- Criminal Empire Online v0.6 — Game Map & Territories seed data

INSERT INTO world_regions (slug, name, description, map_asset, overlay_asset, region_type, travel_cost_cash, travel_cost_energy, base_heat, police_pressure, danger_level, recommended_level, sort_order, is_active, created_at, updated_at) VALUES
('main-city', 'Main City', 'The dense center of Grimwater County: banks, alleys, clubs, rail lines, and police pressure.', '/assets/maps/city/main_city_map.webp', '/assets/maps/city/main_city_overlay.svg', 'city', 5, 2, 28, 58, 45, 1, 10, 1, NOW(), NOW()),
('suburbs', 'Suburbs', 'Comfortable neighborhoods, shopping lots, garages, witnesses, and quieter money.', '/assets/maps/suburbs/suburbs_map.webp', '/assets/maps/suburbs/suburbs_overlay.svg', 'suburbs', 8, 3, 16, 46, 28, 1, 20, 1, NOW(), NOW()),
('industrial-zone', 'Industrial Zone', 'Factories, rail yards, warehouses, loading bays, and dangerous industrial cover.', '/assets/maps/industrial/industrial_zone_map.webp', '/assets/maps/industrial/industrial_zone_overlay.svg', 'industrial', 10, 4, 32, 44, 54, 2, 30, 1, NOW(), NOW()),
('docks', 'Docks', 'Harbor roads, containers, customs gates, ferries, and waterfront movement.', '/assets/maps/docks/docks_map.webp', '/assets/maps/docks/docks_overlay.svg', 'docks', 10, 4, 36, 52, 58, 2, 40, 1, NOW(), NOW()),
('rural-county', 'Rural County', 'Farmlands, motels, barns, scrapyards, and wide roads outside the city.', '/assets/maps/rural/rural_county_map.webp', '/assets/maps/rural/rural_county_overlay.svg', 'rural', 18, 6, 14, 30, 34, 1, 50, 1, NOW(), NOW()),
('forest-hills', 'Forest / Hills', 'Remote cabins, trails, hidden camps, lakes, old mines, and isolation risk.', '/assets/maps/forest/forest_hills_map.webp', '/assets/maps/forest/forest_hills_overlay.svg', 'forest', 22, 7, 12, 22, 42, 2, 60, 1, NOW(), NOW()),
('shore', 'Shore / Beach / Sea', 'Beachfront activity, marina traffic, old piers, caves, and coastal contacts.', '/assets/maps/shore/shore_beach_sea_map.webp', '/assets/maps/shore/shore_beach_sea_overlay.svg', 'shore', 14, 5, 24, 38, 36, 1, 70, 1, NOW(), NOW()),
('old-town', 'Old Town', 'Narrow alleys, old apartments, churches, courthouse square, and forgotten tunnels.', '/assets/maps/old-town/old_town_map.webp', '/assets/maps/old-town/old_town_overlay.svg', 'old_town', 4, 2, 30, 50, 40, 1, 80, 1, NOW(), NOW()),
('outskirts', 'Highway / Outskirts', 'Rest stops, back roads, motel strips, truck parking, and border routes.', '/assets/maps/outskirts/highway_outskirts_map.webp', '/assets/maps/outskirts/highway_outskirts_overlay.svg', 'outskirts', 16, 5, 22, 34, 45, 1, 90, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), map_asset=VALUES(map_asset), overlay_asset=VALUES(overlay_asset), region_type=VALUES(region_type), travel_cost_cash=VALUES(travel_cost_cash), travel_cost_energy=VALUES(travel_cost_energy), base_heat=VALUES(base_heat), police_pressure=VALUES(police_pressure), danger_level=VALUES(danger_level), recommended_level=VALUES(recommended_level), sort_order=VALUES(sort_order), is_active=VALUES(is_active), updated_at=NOW();

INSERT INTO world_locations (region_id, slug, name, description, location_type, x_percent, y_percent, heat_level, police_pressure, danger_level, min_level, linked_feature_key, available_actions_json, sort_order, is_active, created_at, updated_at) VALUES
((SELECT id FROM world_regions WHERE slug='main-city'), 'downtown', 'Downtown', 'Downtown in Grimwater County. A district hotspot with local heat, police pressure, activities, and territory hooks.', 'district', 49.00, 28.00, 38, 65, 42, 1, 'crimes', CAST('["crimes", "quick_crimes", "businesses", "territories"]' AS JSON), 10, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='main-city'), 'slums', 'Slums', 'Slums in Grimwater County. A district hotspot with local heat, police pressure, activities, and territory hooks.', 'district', 21.00, 29.00, 34, 32, 50, 1, 'quick_crimes', CAST('["quick_crimes", "recruitment", "territories"]' AS JSON), 20, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='main-city'), 'market-district', 'Market District', 'Market District in Grimwater County. A black market hotspot with local heat, police pressure, activities, and territory hooks.', 'black_market', 20.00, 56.00, 32, 40, 36, 1, 'quick_crimes', CAST('["quick_crimes", "businesses", "drug_market"]' AS JSON), 30, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='main-city'), 'nightlife-district', 'Nightlife District', 'Nightlife District in Grimwater County. A recruitment hotspot with local heat, police pressure, activities, and territory hooks.', 'recruitment', 71.00, 25.00, 45, 42, 52, 2, 'recruitment', CAST('["recruitment", "dirty_jobs", "businesses"]' AS JSON), 40, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='main-city'), 'police-district', 'Police District', 'Police District in Grimwater County. A police hotspot with local heat, police pressure, activities, and territory hooks.', 'police', 83.00, 40.00, 18, 88, 30, 1, 'heat', CAST('["heat"]' AS JSON), 50, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='main-city'), 'old-town-city', 'Old Town', 'Old Town in Grimwater County. A district hotspot with local heat, police pressure, activities, and territory hooks.', 'district', 72.00, 55.00, 36, 50, 44, 1, 'crimes', CAST('["crimes", "territories"]' AS JSON), 60, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='main-city'), 'train-station', 'Train Station', 'Train Station in Grimwater County. A travel hotspot with local heat, police pressure, activities, and territory hooks.', 'travel', 68.00, 75.00, 30, 55, 40, 1, 'travel', CAST('["travel", "quick_crimes"]' AS JSON), 70, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='main-city'), 'back-alleys', 'Back Alleys', 'Back Alleys in Grimwater County. A crime hotspot with local heat, police pressure, activities, and territory hooks.', 'crime', 49.00, 55.00, 48, 36, 58, 1, 'crimes', CAST('["crimes", "quick_crimes"]' AS JSON), 80, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='main-city'), 'pawn-row', 'Pawn Row', 'Pawn Row in Grimwater County. A black market hotspot with local heat, police pressure, activities, and territory hooks.', 'black_market', 36.00, 62.00, 30, 34, 34, 1, 'equipment', CAST('["equipment", "quick_crimes"]' AS JSON), 90, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='main-city'), 'underground-club', 'Underground Club', 'Underground Club in Grimwater County. A recruitment hotspot with local heat, police pressure, activities, and territory hooks.', 'recruitment', 54.00, 78.00, 42, 38, 55, 2, 'recruitment', CAST('["recruitment", "dirty_jobs"]' AS JSON), 100, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='rural-county'), 'farmlands', 'Farmlands', 'Farmlands in Grimwater County. A district hotspot with local heat, police pressure, activities, and territory hooks.', 'district', 41.00, 22.00, 10, 24, 18, 1, 'jobs', CAST('["jobs", "businesses"]' AS JSON), 110, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='rural-county'), 'roadside-motel', 'Roadside Motel', 'Roadside Motel in Grimwater County. A safehouse hotspot with local heat, police pressure, activities, and territory hooks.', 'safehouse', 17.00, 38.00, 24, 32, 38, 1, 'recruitment', CAST('["recruitment", "dirty_jobs"]' AS JSON), 120, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='rural-county'), 'abandoned-barn', 'Abandoned Barn', 'Abandoned Barn in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 70.00, 23.00, 20, 22, 46, 2, 'crimes', CAST('["crimes", "warehouse"]' AS JSON), 130, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='rural-county'), 'scrapyard', 'Scrapyard', 'Scrapyard in Grimwater County. A garage hotspot with local heat, police pressure, activities, and territory hooks.', 'garage', 85.00, 39.00, 28, 26, 42, 2, 'warehouse', CAST('["warehouse", "equipment", "quick_crimes"]' AS JSON), 140, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='rural-county'), 'county-road', 'County Road', 'County Road in Grimwater County. A travel hotspot with local heat, police pressure, activities, and territory hooks.', 'travel', 23.00, 59.00, 16, 22, 26, 1, 'travel', CAST('["travel"]' AS JSON), 150, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='rural-county'), 'small-town', 'Small Town', 'Small Town in Grimwater County. A district hotspot with local heat, police pressure, activities, and territory hooks.', 'district', 55.00, 55.00, 16, 38, 24, 1, 'jobs', CAST('["jobs", "recruitment"]' AS JSON), 160, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='rural-county'), 'gas-station', 'Gas Station', 'Gas Station in Grimwater County. A business hotspot with local heat, police pressure, activities, and territory hooks.', 'business', 38.00, 77.00, 20, 30, 30, 1, 'businesses', CAST('["businesses", "quick_crimes"]' AS JSON), 170, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='rural-county'), 'trailer-park', 'Trailer Park', 'Trailer Park in Grimwater County. A recruitment hotspot with local heat, police pressure, activities, and territory hooks.', 'recruitment', 74.00, 78.00, 30, 24, 42, 1, 'recruitment', CAST('["recruitment", "quick_crimes"]' AS JSON), 180, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='forest-hills'), 'logging-road', 'Logging Road', 'Logging Road in Grimwater County. A travel hotspot with local heat, police pressure, activities, and territory hooks.', 'travel', 23.00, 22.00, 12, 18, 34, 1, 'travel', CAST('["travel", "jobs"]' AS JSON), 190, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='forest-hills'), 'abandoned-cabin', 'Abandoned Cabin', 'Abandoned Cabin in Grimwater County. A safehouse hotspot with local heat, police pressure, activities, and territory hooks.', 'safehouse', 25.00, 51.00, 20, 18, 48, 2, 'crimes', CAST('["crimes", "warehouse"]' AS JSON), 200, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='forest-hills'), 'hunting-trail', 'Hunting Trail', 'Hunting Trail in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 66.00, 37.00, 14, 14, 42, 1, 'jobs', CAST('["jobs"]' AS JSON), 210, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='forest-hills'), 'hill-lookout', 'Hill Lookout', 'Hill Lookout in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 52.00, 14.00, 16, 18, 36, 1, 'heat', CAST('["heat", "crimes"]' AS JSON), 220, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='forest-hills'), 'hidden-camp', 'Hidden Camp', 'Hidden Camp in Grimwater County. A safehouse hotspot with local heat, police pressure, activities, and territory hooks.', 'safehouse', 50.00, 58.00, 24, 16, 52, 2, 'warehouse', CAST('["warehouse", "recruitment"]' AS JSON), 230, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='forest-hills'), 'forest-lake', 'Forest Lake', 'Forest Lake in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 42.00, 72.00, 8, 12, 28, 1, 'jobs', CAST('["jobs"]' AS JSON), 240, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='forest-hills'), 'old-mine-entrance', 'Old Mine Entrance', 'Old Mine Entrance in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 75.00, 72.00, 26, 18, 58, 3, 'crimes', CAST('["crimes", "dirty_jobs"]' AS JSON), 250, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='shore'), 'public-beach', 'Public Beach', 'Public Beach in Grimwater County. A district hotspot with local heat, police pressure, activities, and territory hooks.', 'district', 43.00, 17.00, 12, 48, 24, 1, 'jobs', CAST('["jobs"]' AS JSON), 260, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='shore'), 'marina', 'Marina', 'Marina in Grimwater County. A business hotspot with local heat, police pressure, activities, and territory hooks.', 'business', 35.00, 49.00, 25, 42, 36, 1, 'businesses', CAST('["businesses", "quick_crimes"]' AS JSON), 270, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='shore'), 'old-pier', 'Old Pier', 'Old Pier in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 55.00, 64.00, 28, 28, 48, 1, 'crimes', CAST('["crimes", "dirty_jobs"]' AS JSON), 280, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='shore'), 'fishing-village', 'Fishing Village', 'Fishing Village in Grimwater County. A district hotspot with local heat, police pressure, activities, and territory hooks.', 'district', 64.00, 29.00, 16, 30, 24, 1, 'jobs', CAST('["jobs", "recruitment"]' AS JSON), 290, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='shore'), 'lighthouse', 'Lighthouse', 'Lighthouse in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 88.00, 25.00, 12, 26, 32, 1, 'crimes', CAST('["crimes"]' AS JSON), 300, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='shore'), 'cargo-shore', 'Cargo Shore', 'Cargo Shore in Grimwater County. A warehouse hotspot with local heat, police pressure, activities, and territory hooks.', 'warehouse', 83.00, 52.00, 36, 42, 54, 2, 'warehouse', CAST('["warehouse", "dirty_jobs"]' AS JSON), 310, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='shore'), 'sea-caves', 'Sea Caves', 'Sea Caves in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 76.00, 78.00, 26, 20, 58, 3, 'crimes', CAST('["crimes"]' AS JSON), 320, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='shore'), 'boardwalk', 'Boardwalk', 'Boardwalk in Grimwater County. A business hotspot with local heat, police pressure, activities, and territory hooks.', 'business', 17.00, 45.00, 22, 38, 34, 1, 'businesses', CAST('["businesses", "quick_crimes"]' AS JSON), 330, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='industrial-zone'), 'factory-blocks', 'Factory Blocks', 'Factory Blocks in Grimwater County. A business hotspot with local heat, police pressure, activities, and territory hooks.', 'business', 42.00, 21.00, 34, 42, 52, 2, 'businesses', CAST('["businesses", "dirty_jobs"]' AS JSON), 340, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='industrial-zone'), 'warehouses', 'Warehouses', 'Warehouses in Grimwater County. A warehouse hotspot with local heat, police pressure, activities, and territory hooks.', 'warehouse', 43.00, 61.00, 36, 38, 56, 1, 'warehouse', CAST('["warehouse", "territories"]' AS JSON), 350, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='industrial-zone'), 'rail-yard', 'Rail Yard', 'Rail Yard in Grimwater County. A travel hotspot with local heat, police pressure, activities, and territory hooks.', 'travel', 27.00, 48.00, 32, 42, 50, 2, 'travel', CAST('["travel", "dirty_jobs"]' AS JSON), 360, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='industrial-zone'), 'power-station', 'Power Station', 'Power Station in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 77.00, 40.00, 22, 58, 48, 3, 'dirty_jobs', CAST('["dirty_jobs"]' AS JSON), 370, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='industrial-zone'), 'loading-bays', 'Loading Bays', 'Loading Bays in Grimwater County. A warehouse hotspot with local heat, police pressure, activities, and territory hooks.', 'warehouse', 83.00, 78.00, 38, 38, 58, 2, 'warehouse', CAST('["warehouse", "quick_crimes"]' AS JSON), 380, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='industrial-zone'), 'workers-bar', 'Workers Bar', 'Workers Bar in Grimwater County. A recruitment hotspot with local heat, police pressure, activities, and territory hooks.', 'recruitment', 22.00, 78.00, 28, 28, 40, 1, 'recruitment', CAST('["recruitment", "dirty_jobs"]' AS JSON), 390, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='industrial-zone'), 'chemical-storage', 'Chemical Storage', 'Chemical Storage in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 82.00, 20.00, 22, 60, 65, 4, 'dirty_jobs', CAST('["dirty_jobs"]' AS JSON), 400, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='docks'), 'container-yard', 'Container Yard', 'Container Yard in Grimwater County. A warehouse hotspot with local heat, police pressure, activities, and territory hooks.', 'warehouse', 15.00, 36.00, 40, 48, 62, 2, 'warehouse', CAST('["warehouse", "dirty_jobs"]' AS JSON), 410, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='docks'), 'dock-office', 'Dock Office', 'Dock Office in Grimwater County. A business hotspot with local heat, police pressure, activities, and territory hooks.', 'business', 48.00, 30.00, 28, 52, 42, 2, 'businesses', CAST('["businesses", "crimes"]' AS JSON), 420, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='docks'), 'dry-dock', 'Dry Dock', 'Dry Dock in Grimwater County. A garage hotspot with local heat, police pressure, activities, and territory hooks.', 'garage', 36.00, 67.00, 34, 36, 50, 2, 'warehouse', CAST('["warehouse", "quick_crimes"]' AS JSON), 430, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='docks'), 'customs-gate', 'Customs Gate', 'Customs Gate in Grimwater County. A police hotspot with local heat, police pressure, activities, and territory hooks.', 'police', 76.00, 35.00, 18, 82, 42, 2, 'heat', CAST('["heat"]' AS JSON), 440, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='docks'), 'ferry-terminal', 'Ferry Terminal', 'Ferry Terminal in Grimwater County. A travel hotspot with local heat, police pressure, activities, and territory hooks.', 'travel', 68.00, 77.00, 24, 46, 36, 1, 'travel', CAST('["travel"]' AS JSON), 450, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='docks'), 'smuggler-pier', 'Smuggler Pier', 'Smuggler Pier in Grimwater County. A black market hotspot with local heat, police pressure, activities, and territory hooks.', 'black_market', 88.00, 55.00, 42, 38, 64, 3, 'dirty_jobs', CAST('["dirty_jobs", "drug_market"]' AS JSON), 460, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='docks'), 'harbor-road', 'Harbor Road', 'Harbor Road in Grimwater County. A travel hotspot with local heat, police pressure, activities, and territory hooks.', 'travel', 53.00, 15.00, 28, 40, 38, 1, 'travel', CAST('["travel", "quick_crimes"]' AS JSON), 470, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='suburbs'), 'residential-blocks', 'Residential Blocks', 'Residential Blocks in Grimwater County. A district hotspot with local heat, police pressure, activities, and territory hooks.', 'district', 33.00, 25.00, 14, 44, 24, 1, 'quick_crimes', CAST('["quick_crimes", "territories"]' AS JSON), 480, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='suburbs'), 'shopping-plaza', 'Shopping Plaza', 'Shopping Plaza in Grimwater County. A business hotspot with local heat, police pressure, activities, and territory hooks.', 'business', 57.00, 39.00, 22, 48, 28, 1, 'businesses', CAST('["businesses", "quick_crimes"]' AS JSON), 490, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='suburbs'), 'school-zone', 'School Zone', 'School Zone in Grimwater County. A police hotspot with local heat, police pressure, activities, and territory hooks.', 'police', 27.00, 55.00, 8, 64, 12, 1, 'jobs', CAST('["jobs"]' AS JSON), 500, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='suburbs'), 'private-estates', 'Private Estates', 'Private Estates in Grimwater County. A district hotspot with local heat, police pressure, activities, and territory hooks.', 'district', 72.00, 28.00, 18, 58, 38, 3, 'crimes', CAST('["crimes", "territories"]' AS JSON), 510, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='suburbs'), 'parking-lots', 'Parking Lots', 'Parking Lots in Grimwater County. A garage hotspot with local heat, police pressure, activities, and territory hooks.', 'garage', 72.00, 53.00, 22, 46, 34, 1, 'quick_crimes', CAST('["quick_crimes"]' AS JSON), 520, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='suburbs'), 'quiet-streets', 'Quiet Streets', 'Quiet Streets in Grimwater County. A safehouse hotspot with local heat, police pressure, activities, and territory hooks.', 'safehouse', 42.00, 67.00, 10, 34, 18, 1, 'heat', CAST('["heat"]' AS JSON), 530, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='suburbs'), 'suburban-garage', 'Suburban Garage', 'Suburban Garage in Grimwater County. A garage hotspot with local heat, police pressure, activities, and territory hooks.', 'garage', 76.00, 72.00, 24, 36, 34, 1, 'equipment', CAST('["equipment", "quick_crimes"]' AS JSON), 540, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='old-town'), 'old-market', 'Old Market', 'Old Market in Grimwater County. A black market hotspot with local heat, police pressure, activities, and territory hooks.', 'black_market', 30.00, 36.00, 34, 42, 36, 1, 'quick_crimes', CAST('["quick_crimes", "businesses"]' AS JSON), 550, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='old-town'), 'old-church', 'Old Church', 'Old Church in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 45.00, 30.00, 12, 34, 22, 1, 'heat', CAST('["heat", "jobs"]' AS JSON), 560, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='old-town'), 'narrow-alleys', 'Narrow Alleys', 'Narrow Alleys in Grimwater County. A crime hotspot with local heat, police pressure, activities, and territory hooks.', 'crime', 42.00, 52.00, 40, 36, 52, 1, 'crimes', CAST('["crimes", "quick_crimes"]' AS JSON), 570, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='old-town'), 'old-apartments', 'Old Apartments', 'Old Apartments in Grimwater County. A district hotspot with local heat, police pressure, activities, and territory hooks.', 'district', 62.00, 41.00, 32, 44, 46, 1, 'recruitment', CAST('["recruitment", "territories"]' AS JSON), 580, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='old-town'), 'antique-shops', 'Antique Shops', 'Antique Shops in Grimwater County. A business hotspot with local heat, police pressure, activities, and territory hooks.', 'business', 69.00, 58.00, 24, 38, 32, 1, 'businesses', CAST('["businesses", "quick_crimes"]' AS JSON), 590, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='old-town'), 'courthouse-square', 'Courthouse Square', 'Courthouse Square in Grimwater County. A police hotspot with local heat, police pressure, activities, and territory hooks.', 'police', 55.00, 70.00, 16, 72, 30, 2, 'heat', CAST('["heat"]' AS JSON), 600, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='old-town'), 'basement-bars', 'Basement Bars', 'Basement Bars in Grimwater County. A recruitment hotspot with local heat, police pressure, activities, and territory hooks.', 'recruitment', 34.00, 70.00, 36, 34, 48, 1, 'recruitment', CAST('["recruitment", "dirty_jobs"]' AS JSON), 610, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='old-town'), 'forgotten-tunnels', 'Forgotten Tunnels', 'Forgotten Tunnels in Grimwater County. A point of interest hotspot with local heat, police pressure, activities, and territory hooks.', 'point_of_interest', 75.00, 78.00, 38, 28, 64, 3, 'crimes', CAST('["crimes"]' AS JSON), 620, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='outskirts'), 'highway-rest-stop', 'Highway Rest Stop', 'Highway Rest Stop in Grimwater County. A travel hotspot with local heat, police pressure, activities, and territory hooks.', 'travel', 38.00, 30.00, 20, 34, 28, 1, 'travel', CAST('["travel", "jobs"]' AS JSON), 630, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='outskirts'), 'truck-parking', 'Truck Parking', 'Truck Parking in Grimwater County. A garage hotspot with local heat, police pressure, activities, and territory hooks.', 'garage', 52.00, 28.00, 26, 32, 42, 1, 'quick_crimes', CAST('["quick_crimes", "dirty_jobs"]' AS JSON), 640, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='outskirts'), 'abandoned-gas-station', 'Abandoned Gas Station', 'Abandoned Gas Station in Grimwater County. A safehouse hotspot with local heat, police pressure, activities, and territory hooks.', 'safehouse', 62.00, 41.00, 28, 22, 52, 2, 'warehouse', CAST('["warehouse", "crimes"]' AS JSON), 650, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='outskirts'), 'overpass', 'Overpass', 'Overpass in Grimwater County. A travel hotspot with local heat, police pressure, activities, and territory hooks.', 'travel', 44.00, 52.00, 22, 36, 38, 1, 'travel', CAST('["travel"]' AS JSON), 660, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='outskirts'), 'motel-strip', 'Motel Strip', 'Motel Strip in Grimwater County. A recruitment hotspot with local heat, police pressure, activities, and territory hooks.', 'recruitment', 31.00, 67.00, 34, 30, 48, 1, 'recruitment', CAST('["recruitment", "dirty_jobs"]' AS JSON), 670, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='outskirts'), 'back-road', 'Back Road', 'Back Road in Grimwater County. A travel hotspot with local heat, police pressure, activities, and territory hooks.', 'travel', 60.00, 66.00, 20, 22, 44, 1, 'travel', CAST('["travel", "quick_crimes"]' AS JSON), 680, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='outskirts'), 'junkyard-entrance', 'Junkyard Entrance', 'Junkyard Entrance in Grimwater County. A garage hotspot with local heat, police pressure, activities, and territory hooks.', 'garage', 76.00, 59.00, 30, 28, 46, 2, 'warehouse', CAST('["warehouse", "equipment"]' AS JSON), 690, 1, NOW(), NOW()),
((SELECT id FROM world_regions WHERE slug='outskirts'), 'border-road', 'Border Road', 'Border Road in Grimwater County. A travel hotspot with local heat, police pressure, activities, and territory hooks.', 'travel', 82.00, 78.00, 24, 44, 54, 3, 'travel', CAST('["travel", "dirty_jobs"]' AS JSON), 700, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE region_id=VALUES(region_id), name=VALUES(name), description=VALUES(description), location_type=VALUES(location_type), x_percent=VALUES(x_percent), y_percent=VALUES(y_percent), heat_level=VALUES(heat_level), police_pressure=VALUES(police_pressure), danger_level=VALUES(danger_level), min_level=VALUES(min_level), linked_feature_key=VALUES(linked_feature_key), available_actions_json=VALUES(available_actions_json), sort_order=VALUES(sort_order), is_active=VALUES(is_active), updated_at=NOW();

UPDATE world_locations SET linked_territory_id = (SELECT id FROM territories WHERE name = 'Downtown' LIMIT 1) WHERE slug = 'downtown';
UPDATE world_locations SET linked_territory_id = (SELECT id FROM territories WHERE name = 'Old Town' LIMIT 1) WHERE slug = 'old-town-city';
UPDATE world_locations SET linked_territory_id = (SELECT id FROM territories WHERE name = 'Industrial Zone' LIMIT 1) WHERE slug = 'warehouses';
UPDATE world_locations SET linked_territory_id = (SELECT id FROM territories WHERE name = 'Harbor' LIMIT 1) WHERE slug = 'harbor-road';
UPDATE world_locations SET linked_territory_id = (SELECT id FROM territories WHERE name = 'Luxury Hills' LIMIT 1) WHERE slug = 'private-estates';
UPDATE world_locations SET linked_territory_id = (SELECT id FROM territories WHERE name = 'Old Town' LIMIT 1) WHERE slug = 'old-apartments';

INSERT INTO map_activity_links (world_location_id, feature_type, feature_key, label, route_hint, min_level, is_active, sort_order, created_at, updated_at) VALUES
((SELECT id FROM world_locations WHERE slug='downtown'), 'crimes', 'crimes', 'View Crimes', 'crimes', 1, 1, 10, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='downtown'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 20, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='downtown'), 'businesses', 'businesses', 'Businesses', 'territories', 1, 1, 30, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='downtown'), 'territories', 'territories', 'Territory Details', 'territories', 1, 1, 40, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='slums'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 50, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='slums'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 1, 1, 60, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='slums'), 'territories', 'territories', 'Territory Details', 'territories', 1, 1, 70, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='market-district'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 80, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='market-district'), 'businesses', 'businesses', 'Businesses', 'territories', 1, 1, 90, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='market-district'), 'drug_market', 'drug_market', 'Drug Market', 'market', 1, 1, 100, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='nightlife-district'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 2, 1, 110, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='nightlife-district'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 2, 1, 120, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='nightlife-district'), 'businesses', 'businesses', 'Businesses', 'territories', 2, 1, 130, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='police-district'), 'heat', 'heat', 'Heat & Police', 'heat', 1, 1, 140, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-town-city'), 'crimes', 'crimes', 'View Crimes', 'crimes', 1, 1, 150, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-town-city'), 'territories', 'territories', 'Territory Details', 'territories', 1, 1, 160, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='train-station'), 'travel', 'travel', 'Travel Route', 'world map', 1, 1, 170, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='train-station'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 180, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='back-alleys'), 'crimes', 'crimes', 'View Crimes', 'crimes', 1, 1, 190, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='back-alleys'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 200, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='pawn-row'), 'equipment', 'equipment', 'Inventory / Gear', 'equipment', 1, 1, 210, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='pawn-row'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 220, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='underground-club'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 2, 1, 230, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='underground-club'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 2, 1, 240, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='farmlands'), 'jobs', 'jobs', 'Street Jobs', 'jobs', 1, 1, 250, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='farmlands'), 'businesses', 'businesses', 'Businesses', 'territories', 1, 1, 260, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='roadside-motel'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 1, 1, 270, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='roadside-motel'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 1, 1, 280, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='abandoned-barn'), 'crimes', 'crimes', 'View Crimes', 'crimes', 2, 1, 290, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='abandoned-barn'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 2, 1, 300, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='scrapyard'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 2, 1, 310, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='scrapyard'), 'equipment', 'equipment', 'Inventory / Gear', 'equipment', 2, 1, 320, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='scrapyard'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 2, 1, 330, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='county-road'), 'travel', 'travel', 'Travel Route', 'world map', 1, 1, 340, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='small-town'), 'jobs', 'jobs', 'Street Jobs', 'jobs', 1, 1, 350, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='small-town'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 1, 1, 360, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='gas-station'), 'businesses', 'businesses', 'Businesses', 'territories', 1, 1, 370, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='gas-station'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 380, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='trailer-park'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 1, 1, 390, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='trailer-park'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 400, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='logging-road'), 'travel', 'travel', 'Travel Route', 'world map', 1, 1, 410, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='logging-road'), 'jobs', 'jobs', 'Street Jobs', 'jobs', 1, 1, 420, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='abandoned-cabin'), 'crimes', 'crimes', 'View Crimes', 'crimes', 2, 1, 430, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='abandoned-cabin'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 2, 1, 440, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='hunting-trail'), 'jobs', 'jobs', 'Street Jobs', 'jobs', 1, 1, 450, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='hill-lookout'), 'heat', 'heat', 'Heat & Police', 'heat', 1, 1, 460, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='hill-lookout'), 'crimes', 'crimes', 'View Crimes', 'crimes', 1, 1, 470, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='hidden-camp'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 2, 1, 480, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='hidden-camp'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 2, 1, 490, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='forest-lake'), 'jobs', 'jobs', 'Street Jobs', 'jobs', 1, 1, 500, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-mine-entrance'), 'crimes', 'crimes', 'View Crimes', 'crimes', 3, 1, 510, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-mine-entrance'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 3, 1, 520, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='public-beach'), 'jobs', 'jobs', 'Street Jobs', 'jobs', 1, 1, 530, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='marina'), 'businesses', 'businesses', 'Businesses', 'territories', 1, 1, 540, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='marina'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 550, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-pier'), 'crimes', 'crimes', 'View Crimes', 'crimes', 1, 1, 560, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-pier'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 1, 1, 570, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='fishing-village'), 'jobs', 'jobs', 'Street Jobs', 'jobs', 1, 1, 580, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='fishing-village'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 1, 1, 590, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='lighthouse'), 'crimes', 'crimes', 'View Crimes', 'crimes', 1, 1, 600, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='cargo-shore'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 2, 1, 610, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='cargo-shore'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 2, 1, 620, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='sea-caves'), 'crimes', 'crimes', 'View Crimes', 'crimes', 3, 1, 630, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='boardwalk'), 'businesses', 'businesses', 'Businesses', 'territories', 1, 1, 640, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='boardwalk'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 650, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='factory-blocks'), 'businesses', 'businesses', 'Businesses', 'territories', 2, 1, 660, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='factory-blocks'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 2, 1, 670, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='warehouses'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 1, 1, 680, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='warehouses'), 'territories', 'territories', 'Territory Details', 'territories', 1, 1, 690, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='rail-yard'), 'travel', 'travel', 'Travel Route', 'world map', 2, 1, 700, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='rail-yard'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 2, 1, 710, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='power-station'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 3, 1, 720, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='loading-bays'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 2, 1, 730, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='loading-bays'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 2, 1, 740, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='workers-bar'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 1, 1, 750, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='workers-bar'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 1, 1, 760, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='chemical-storage'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 4, 1, 770, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='container-yard'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 2, 1, 780, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='container-yard'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 2, 1, 790, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='dock-office'), 'businesses', 'businesses', 'Businesses', 'territories', 2, 1, 800, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='dock-office'), 'crimes', 'crimes', 'View Crimes', 'crimes', 2, 1, 810, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='dry-dock'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 2, 1, 820, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='dry-dock'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 2, 1, 830, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='customs-gate'), 'heat', 'heat', 'Heat & Police', 'heat', 2, 1, 840, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='ferry-terminal'), 'travel', 'travel', 'Travel Route', 'world map', 1, 1, 850, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='smuggler-pier'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 3, 1, 860, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='smuggler-pier'), 'drug_market', 'drug_market', 'Drug Market', 'market', 3, 1, 870, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='harbor-road'), 'travel', 'travel', 'Travel Route', 'world map', 1, 1, 880, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='harbor-road'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 890, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='residential-blocks'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 900, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='residential-blocks'), 'territories', 'territories', 'Territory Details', 'territories', 1, 1, 910, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='shopping-plaza'), 'businesses', 'businesses', 'Businesses', 'territories', 1, 1, 920, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='shopping-plaza'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 930, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='school-zone'), 'jobs', 'jobs', 'Street Jobs', 'jobs', 1, 1, 940, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='private-estates'), 'crimes', 'crimes', 'View Crimes', 'crimes', 3, 1, 950, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='private-estates'), 'territories', 'territories', 'Territory Details', 'territories', 3, 1, 960, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='parking-lots'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 970, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='quiet-streets'), 'heat', 'heat', 'Heat & Police', 'heat', 1, 1, 980, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='suburban-garage'), 'equipment', 'equipment', 'Inventory / Gear', 'equipment', 1, 1, 990, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='suburban-garage'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 1000, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-market'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 1010, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-market'), 'businesses', 'businesses', 'Businesses', 'territories', 1, 1, 1020, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-church'), 'heat', 'heat', 'Heat & Police', 'heat', 1, 1, 1030, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-church'), 'jobs', 'jobs', 'Street Jobs', 'jobs', 1, 1, 1040, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='narrow-alleys'), 'crimes', 'crimes', 'View Crimes', 'crimes', 1, 1, 1050, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='narrow-alleys'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 1060, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-apartments'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 1, 1, 1070, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='old-apartments'), 'territories', 'territories', 'Territory Details', 'territories', 1, 1, 1080, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='antique-shops'), 'businesses', 'businesses', 'Businesses', 'territories', 1, 1, 1090, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='antique-shops'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 1100, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='courthouse-square'), 'heat', 'heat', 'Heat & Police', 'heat', 2, 1, 1110, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='basement-bars'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 1, 1, 1120, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='basement-bars'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 1, 1, 1130, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='forgotten-tunnels'), 'crimes', 'crimes', 'View Crimes', 'crimes', 3, 1, 1140, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='highway-rest-stop'), 'travel', 'travel', 'Travel Route', 'world map', 1, 1, 1150, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='highway-rest-stop'), 'jobs', 'jobs', 'Street Jobs', 'jobs', 1, 1, 1160, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='truck-parking'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 1170, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='truck-parking'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 1, 1, 1180, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='abandoned-gas-station'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 2, 1, 1190, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='abandoned-gas-station'), 'crimes', 'crimes', 'View Crimes', 'crimes', 2, 1, 1200, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='overpass'), 'travel', 'travel', 'Travel Route', 'world map', 1, 1, 1210, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='motel-strip'), 'recruitment', 'recruitment', 'Recruit Nearby', 'recruitment', 1, 1, 1220, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='motel-strip'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 1, 1, 1230, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='back-road'), 'travel', 'travel', 'Travel Route', 'world map', 1, 1, 1240, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='back-road'), 'quick_crimes', 'quick_crimes', 'Quick Crimes', 'crimes', 1, 1, 1250, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='junkyard-entrance'), 'warehouse', 'warehouse', 'Warehouse', 'warehouse', 2, 1, 1260, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='junkyard-entrance'), 'equipment', 'equipment', 'Inventory / Gear', 'equipment', 2, 1, 1270, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='border-road'), 'travel', 'travel', 'Travel Route', 'world map', 3, 1, 1280, NOW(), NOW()),
((SELECT id FROM world_locations WHERE slug='border-road'), 'dirty_jobs', 'dirty_jobs', 'Dirty Jobs', 'dirty jobs', 3, 1, 1290, NOW(), NOW())
ON DUPLICATE KEY UPDATE label=VALUES(label), route_hint=VALUES(route_hint), min_level=VALUES(min_level), is_active=VALUES(is_active), sort_order=VALUES(sort_order), updated_at=NOW();

INSERT INTO territory_map_links (territory_id, world_region_id, world_location_id, control_display_mode, is_primary, created_at, updated_at)
SELECT territory.id, region.id, location.id, 'normal', 1, NOW(), NOW()
FROM world_locations location
JOIN world_regions region ON region.id = location.region_id
JOIN territories territory ON territory.id = location.linked_territory_id
WHERE location.linked_territory_id IS NOT NULL
ON DUPLICATE KEY UPDATE world_location_id=VALUES(world_location_id), updated_at=NOW();

INSERT INTO user_location_state (user_id, current_region_id, current_location_id, created_at, updated_at)
SELECT users.id, region.id, location.id, NOW(), NOW()
FROM users
JOIN world_regions region ON region.slug = 'main-city'
JOIN world_locations location ON location.slug = 'slums'
WHERE NOT EXISTS (SELECT 1 FROM user_location_state state WHERE state.user_id = users.id);

INSERT INTO update_notices (version, title, body, active, created_at, updated_at) SELECT '0.6.0', 'v0.6 — Game Map & Territories', 'v0.6 adds the Grimwater County world map, clickable regions, sub-map hotspots, travel/current location, territory links, map risk display, and local map assets.', 1, NOW(), NOW() FROM DUAL WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = 'update_notices') AND NOT EXISTS (SELECT 1 FROM update_notices WHERE version = '0.6.0');
