-- Criminal Empire Online v0.7 — UX Navigation & Inventory Loadout Expansion seed/config update

UPDATE item_definitions SET
  size_class = 'small', carry_units = 1.00, stack_limit = 1,
  allowed_slots = JSON_ARRAY('hands'), item_tags = JSON_ARRAY('evidence_safety','workwear'),
  item_effects = JSON_OBJECT('evidence_risk_multiplier', 0.85, 'forced_entry_bonus', 1),
  legality = 'legal', visible_illegal = 0, concealment_rating = 95,
  is_equippable = 1, is_carryable = 1
WHERE code IN ('work_gloves', 'gloves');

UPDATE item_definitions SET allowed_slots = JSON_ARRAY('head','disguise'), item_tags = JSON_ARRAY('identity_cover'), item_effects = JSON_OBJECT('witness_identification_multiplier', 0.75, 'police_suspicion_bonus', 2), size_class = 'tiny', carry_units = 0.50, legality = 'legal' WHERE code IN ('face_covering','mask');
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('torso','disguise'), item_tags = JSON_ARRAY('stealth','clothing'), item_effects = JSON_OBJECT('stealth_bonus', 4, 'witness_identification_multiplier', 0.9), size_class = 'medium', carry_units = 2.00, legality = 'legal' WHERE code = 'dark_clothing';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('torso','disguise'), item_tags = JSON_ARRAY('disguise','industrial'), item_effects = JSON_OBJECT('disguise_bonus', 5), size_class = 'medium', carry_units = 2.00, legality = 'legal' WHERE code = 'work_uniform';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('armor','torso'), item_tags = JSON_ARRAY('armor','bulky'), item_effects = JSON_OBJECT('injury_reduction', 6, 'stealth_bonus', -3, 'mobility_penalty', 3), size_class = 'large', carry_units = 3.00, legality = 'restricted', visible_illegal = 1, concealment_rating = 20 WHERE code = 'basic_vest';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('melee'), item_tags = JSON_ARRAY('weapon','illegal_visible'), item_effects = JSON_OBJECT('intimidation_bonus', 5, 'heat_multiplier', 1.15), size_class = 'small', carry_units = 1.00, legality = 'illegal', visible_illegal = 1, concealment_rating = 35 WHERE code IN ('cheap_knife','knife');
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('sidearm'), item_tags = JSON_ARRAY('weapon','firearm','illegal_visible'), item_effects = JSON_OBJECT('intimidation_bonus', 12, 'heat_multiplier', 1.5, 'police_suspicion_bonus', 10), size_class = 'small', carry_units = 1.50, legality = 'illegal', visible_illegal = 1, concealment_rating = 25 WHERE code = 'basic_pistol';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('tool'), item_tags = JSON_ARRAY('forced_entry','noisy','bulky'), item_effects = JSON_OBJECT('forced_entry_bonus', 7, 'noise_penalty', 4, 'police_suspicion_bonus', 3), size_class = 'medium', carry_units = 2.00, legality = 'suspicious', visible_illegal = 1, concealment_rating = 40 WHERE code = 'crowbar';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('tool'), item_tags = JSON_ARRAY('stealth_entry','illegal_tool'), item_effects = JSON_OBJECT('stealth_bonus', 5, 'forced_entry_bonus', 2, 'police_suspicion_bonus', 2), size_class = 'tiny', carry_units = 0.50, legality = 'suspicious', visible_illegal = 0, concealment_rating = 75 WHERE code = 'lockpick_set';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('tool'), item_tags = JSON_ARRAY('vehicle_crime','tool'), item_effects = JSON_OBJECT('vehicle_crime_bonus', 5), size_class = 'small', carry_units = 1.00, legality = 'legal', visible_illegal = 0, concealment_rating = 80 WHERE code = 'screwdriver_set';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('tool'), item_tags = JSON_ARRAY('vehicle_crime','repair','bulky'), item_effects = JSON_OBJECT('vehicle_crime_bonus', 8, 'police_suspicion_bonus', 2), size_class = 'medium', carry_units = 2.00, legality = 'suspicious', visible_illegal = 0, concealment_rating = 55 WHERE code = 'vehicle_tools';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('tool'), item_tags = JSON_ARRAY('entry_tool'), item_effects = JSON_OBJECT('forced_entry_bonus', 4, 'noise_penalty', 2), size_class = 'small', carry_units = 1.00, legality = 'suspicious' WHERE code = 'glass_breaker';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('utility_1','utility_2'), item_tags = JSON_ARRAY('utility','low_light'), item_effects = JSON_OBJECT('utility', 2), size_class = 'small', carry_units = 1.00, legality = 'legal' WHERE code = 'flashlight';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('bag'), item_tags = JSON_ARRAY('bag','carry'), item_effects = JSON_OBJECT('carry_capacity_bonus', 4, 'loot_capacity_bonus', 4, 'mobility_penalty', 3, 'police_suspicion_bonus', 2), size_class = 'large', carry_units = 3.00, legality = 'legal' WHERE code = 'duffel_bag';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('bag'), item_tags = JSON_ARRAY('bag','carry'), item_effects = JSON_OBJECT('carry_capacity_bonus', 2, 'loot_capacity_bonus', 2, 'mobility_penalty', 1), size_class = 'medium', carry_units = 2.00, legality = 'legal' WHERE code = 'backpack';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('utility_1','utility_2'), item_tags = JSON_ARRAY('medical','event_unlock'), item_effects = JSON_OBJECT('first_aid_event_unlock', 1, 'injury_reduction', 2), size_class = 'small', carry_units = 1.00, legality = 'legal' WHERE code = 'first_aid_kit';
UPDATE item_definitions SET allowed_slots = JSON_ARRAY('utility_1','utility_2'), item_tags = JSON_ARRAY('contact_safety'), item_effects = JSON_OBJECT('contact_exposure_reduction', 4, 'police_suspicion_bonus', 1), size_class = 'tiny', carry_units = 0.50, legality = 'suspicious' WHERE code = 'burner_phone';

UPDATE shops SET accepted_payment_types_json = JSON_ARRAY('cash'), accepts_clean_cash = 1, accepts_bank = 0, accepts_dirty_money = 0, sale_visibility = 'legal' WHERE is_legal = 1;
UPDATE shops SET accepted_payment_types_json = JSON_ARRAY('cash','dirty_money'), accepts_clean_cash = 1, accepts_bank = 0, accepts_dirty_money = 1, dirty_money_markup = 1.00, sale_visibility = 'shady' WHERE is_legal = 0 AND is_black_market = 0;
UPDATE shops SET accepted_payment_types_json = JSON_ARRAY('dirty_money','cash'), accepts_clean_cash = 1, accepts_bank = 0, accepts_dirty_money = 1, dirty_money_markup = 0.95, clean_cash_markup = 1.15, sale_visibility = 'black_market' WHERE is_black_market = 1;
