-- Criminal Empire Online v0.7.3 — Loadout UX & Carry Inventory Polish seed/config update

UPDATE item_definitions SET item_role = 'equipped_gear', carry_role = 'equip_only', preferred_equipment_slot = 'hands', is_consumable = 0, is_task_item = 0, can_satisfy_task_requirement = 1, carry_behavior = 'do_not_carry', use_behavior = 'evidence_safety' WHERE code IN ('work_gloves', 'gloves');
UPDATE item_definitions SET item_role = 'equipped_gear', carry_role = 'equip_only', preferred_equipment_slot = 'head', carry_behavior = 'do_not_carry', use_behavior = 'identity_cover' WHERE code IN ('face_covering','mask');
UPDATE item_definitions SET item_role = 'equipped_gear', carry_role = 'equip_only', preferred_equipment_slot = 'torso', carry_behavior = 'do_not_carry', use_behavior = 'stealth_clothing' WHERE code IN ('dark_clothing','work_uniform');
UPDATE item_definitions SET item_role = 'armor', carry_role = 'equip_only', preferred_equipment_slot = 'armor', carry_behavior = 'do_not_carry', use_behavior = 'injury_protection' WHERE code = 'basic_vest';
UPDATE item_definitions SET item_role = 'weapon', carry_role = 'equip_only', preferred_equipment_slot = 'melee', carry_behavior = 'do_not_carry', use_behavior = 'intimidation' WHERE code IN ('cheap_knife','knife');
UPDATE item_definitions SET item_role = 'tool', carry_role = 'carry_tool', preferred_equipment_slot = 'tool', is_task_item = 1, can_satisfy_task_requirement = 1, carry_behavior = 'task_tool', use_behavior = 'entry_or_vehicle_tool' WHERE code IN ('crowbar','lockpick_set','screwdriver_set','vehicle_tools','glass_breaker');
UPDATE item_definitions SET item_role = 'utility', carry_role = 'crime_utility', preferred_equipment_slot = 'utility_1', is_task_item = 1, can_satisfy_task_requirement = 1, carry_behavior = 'bring_for_task', use_behavior = 'utility_choice' WHERE code IN ('flashlight','burner_phone');
UPDATE item_definitions SET item_role = 'consumable', carry_role = 'consumable', preferred_equipment_slot = NULL, is_consumable = 1, is_task_item = 1, can_satisfy_task_requirement = 1, is_equippable = 0, is_carryable = 1, carry_behavior = 'consumable', use_behavior = 'first_aid_event' WHERE code IN ('first_aid_kit','bandages');
UPDATE item_definitions SET item_role = 'equipped_gear', carry_role = 'equip_only', preferred_equipment_slot = 'bag', carry_behavior = 'do_not_carry', use_behavior = 'carry_capacity' WHERE code IN ('duffel_bag','backpack');
UPDATE item_definitions SET item_role = 'task_item', carry_role = 'task_item', is_task_item = 1, can_satisfy_task_requirement = 1, is_equippable = 0, is_carryable = 1, carry_behavior = 'task_item', use_behavior = 'production_or_loot' WHERE category IN ('production_supply','stolen_good','vehicle_part');
