import React, {useEffect, useState} from 'react';
import { createRoot } from 'react-dom/client';
import './styles/app.css';
import { api, clearToken, getToken, setToken } from './api/client';

type User = {id:number; username:string; email:string; role:string; cash:number; bank_cash:number; energy:number; max_energy:number; heat:number; level:number; experience:number; strength:number; intelligence:number; charisma:number; combat:number; leadership:number};
type Crime = {id:number; name:string; description:string; energy_cost:number; success_rate:number; reward_min:number; reward_max:number; heat_gain:number; experience_gain:number};
type Weapon = {id:number; name:string; class:string; damage:number; accuracy:number; reliability:number; concealment:number; price:number};

function App(){
  const [user,setUser]=useState<User|null>(null); const [page,setPage]=useState('dashboard'); const [error,setError]=useState('');
  async function refresh(){ if(!getToken()) return; try{ const r=await api<{user:User}>('/me'); setUser(r.user);}catch{clearToken(); setUser(null);} }
  useEffect(()=>{refresh()},[]);
  if(!user) return <Auth onLogin={(u)=>setUser(u)} error={error} setError={setError}/>;
  return <div className="app"><nav className="nav"><div className="brand">Criminal Empire</div>{['dashboard','crimes','weapons','inventory','market','gangs','territories'].map(p=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}>{p}</button>)}{user.role==='admin'&&<button onClick={()=>setPage('admin')}>admin</button>}<button onClick={()=>{clearToken();setUser(null)}}>logout</button></nav><main className="container"><Stats user={user}/>{page==='dashboard'&&<Dashboard/>}{page==='crimes'&&<Crimes refresh={refresh}/>} {page==='weapons'&&<Weapons refresh={refresh}/>} {page==='inventory'&&<Inventory/>}{page==='market'&&<DrugMarket/>}{page==='gangs'&&<Gangs/>}{page==='territories'&&<Territories/>}{page==='admin'&&<Admin/>}</main></div>
}
function Auth({onLogin,error,setError}:{onLogin:(u:User)=>void;error:string;setError:(e:string)=>void}){const [mode,setMode]=useState<'login'|'register'>('login'); const [form,setForm]=useState({username:'',email:'admin@criminal.test',password:'password'}); async function submit(){try{setError(''); const r=await api<{token:string;user:User}>(mode==='login'?'/login':'/register',{method:'POST',body:JSON.stringify(form)}); setToken(r.token); onLogin(r.user);}catch(e:any){setError(e.message)}} return <div className="container"><div className="card" style={{maxWidth:420,margin:'8vh auto'}}><h1>Criminal Empire Online</h1><p className="muted">v0.1 MVP</p>{mode==='register'&&<input placeholder="username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/>}<input placeholder="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<p className="danger">{error}</p>}<button className="btn primary" onClick={submit}>{mode}</button><button className="btn" onClick={()=>setMode(mode==='login'?'register':'login')}>switch to {mode==='login'?'register':'login'}</button></div></div>}
function Stats({user}:{user:User}){return <div className="grid"><div className="card"><div className="muted">Cash</div><div className="stat">${user.cash.toLocaleString()}</div></div><div className="card"><div className="muted">Energy</div><div className="stat">{user.energy}/{user.max_energy}</div></div><div className="card"><div className="muted">Heat</div><div className="stat danger">{user.heat}</div></div><div className="card"><div className="muted">Level / XP</div><div className="stat">{user.level} / {user.experience}</div></div></div>}
function Dashboard(){return <div className="card"><h2>Empire Overview</h2><p>Commit crimes, earn cash, buy weapons, watch the drug market, create gangs, and fight for territories. This is the v0.1 playable foundation.</p></div>}
function Crimes({refresh}:{refresh:()=>void}){const [items,setItems]=useState<Crime[]>([]);const [msg,setMsg]=useState('');useEffect(()=>{api<{data:Crime[]}>('/crimes').then(r=>setItems(r.data))},[]);async function commit(id:number){try{const r=await api<any>(`/crimes/${id}/commit`,{method:'POST'});setMsg(r.success?`Success! Earned $${r.reward}`:`Failed. Heat +${r.heat_gained}`);refresh()}catch(e:any){setMsg(e.message)}}return <><h2>Crimes</h2>{msg&&<div className="card">{msg}</div>}<div className="grid">{items.map(c=><div className="card" key={c.id}><h3>{c.name}</h3><p className="muted">{c.description}</p><p>Energy: {c.energy_cost} | Success: {c.success_rate}% | Heat: +{c.heat_gain}</p><p>Reward: ${c.reward_min} - ${c.reward_max}</p><button className="btn primary" onClick={()=>commit(c.id)}>Commit</button></div>)}</div></>}
function Weapons({refresh}:{refresh:()=>void}){const [items,setItems]=useState<Weapon[]>([]);const [msg,setMsg]=useState('');useEffect(()=>{api<{data:Weapon[]}>('/weapons').then(r=>setItems(r.data))},[]);async function buy(id:number){try{const r=await api<any>(`/weapons/${id}/buy`,{method:'POST'});setMsg(r.message);refresh()}catch(e:any){setMsg(e.message)}}return <><h2>Weapon Shop</h2>{msg&&<div className="card">{msg}</div>}<div className="grid">{items.map(w=><div className="card" key={w.id}><h3>{w.name}</h3><p>{w.class}</p><p>Damage {w.damage} | Accuracy {w.accuracy} | Concealment {w.concealment}</p><p>${w.price.toLocaleString()}</p><button className="btn primary" onClick={()=>buy(w.id)}>Buy</button></div>)}</div></>}
function Inventory(){const [data,setData]=useState<any>({weapons:[],drugs:[]});useEffect(()=>{api<any>('/inventory').then(setData)},[]);return <div className="grid"><div className="card"><h2>Weapons</h2>{data.weapons.map((x:any)=><p key={x.id}>{x.name} × {x.quantity}</p>)}</div><div className="card"><h2>Drugs</h2>{data.drugs.map((x:any)=><p key={x.id}>{x.name} × {x.quantity}</p>)}</div></div>}
function DrugMarket(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{api<any>('/drug-market').then(r=>setItems(r.data))},[]);return <div className="card"><h2>Drug Market</h2><table className="table"><tbody>{items.map((d,i)=><tr key={i}><td>{d.region}</td><td>{d.name}</td><td>${Number(d.price).toLocaleString()}</td><td>Supply {d.supply}</td><td>Demand {d.demand}</td><td>Police {d.police_pressure}</td></tr>)}</tbody></table></div>}
function Gangs(){const [items,setItems]=useState<any[]>([]); const [name,setName]=useState(''); async function load(){const r=await api<any>('/gangs');setItems(r.data)} useEffect(()=>{load()},[]); async function create(){await api('/gangs',{method:'POST',body:JSON.stringify({name})});setName('');load()} return <div className="card"><h2>Gangs</h2><div className="row"><input placeholder="Gang name" value={name} onChange={e=>setName(e.target.value)}/><button className="btn primary" onClick={create}>Create</button></div>{items.map(g=><p key={g.id}>{g.name} — reputation {g.reputation} — treasury ${g.treasury}</p>)}</div>}
function Territories(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{api<any>('/territories').then(r=>setItems(r.data))},[]);return <div className="grid">{items.map(t=><div className="card" key={t.id}><h3>{t.name}</h3><p>Population {Number(t.population).toLocaleString()}</p><p>Wealth {t.wealth} | Crime {t.crime_rate} | Govt {t.government_presence}</p><p>Owner: {t.owner_gang || 'Uncontrolled'}</p></div>)}</div>}
function Admin(){const [stats,setStats]=useState<any>(null);const [logs,setLogs]=useState<any[]>([]);useEffect(()=>{api<any>('/admin/dashboard').then(r=>setStats(r.stats));api<any>('/admin/audit').then(r=>setLogs(r.data))},[]);return <div className="card"><h2>Admin</h2><pre>{JSON.stringify(stats,null,2)}</pre><h3>Audit</h3>{logs.map(l=><p key={l.id}>{l.created_at} — {l.action}</p>)}</div>}

createRoot(document.getElementById('root')!).render(<App/>);
