import React, {useEffect, useState} from 'react';
import { createRoot } from 'react-dom/client';
import './styles/app.css';
import { api, clearToken, getToken, setToken } from './api/client';

type User = {id:number; username:string; email:string; role:string; cash:number; bank_cash:number; dirty_money:number; reputation:number; energy:number; max_energy:number; heat:number; level:number; experience:number; strength:number; intelligence:number; charisma:number; combat:number; leadership:number};
type Crime = {id:number; name:string; description:string; energy_cost:number; success_rate:number; reward_min:number; reward_max:number; heat_gain:number; experience_gain:number};
type Weapon = {id:number; name:string; class:string; damage:number; accuracy:number; reliability:number; concealment:number; price:number};

function App(){
  const [user,setUser]=useState<User|null>(null); const [page,setPage]=useState('dashboard'); const [error,setError]=useState('');
  async function refresh(){ if(!getToken()) return; try{ const r=await api<{user:User}>('/me'); setUser(r.user);}catch{clearToken(); setUser(null);} }
  useEffect(()=>{refresh()},[]);
  if(!user) return <Auth onLogin={(u)=>setUser(u)} error={error} setError={setError}/>;
  return <div className="app"><nav className="nav"><div className="brand">Criminal Empire</div>{['dashboard','jobs','recruitment','my gang','crimes','weapons','inventory','market','territories'].map(p=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}>{p}</button>)}{user.role==='admin'&&<button onClick={()=>setPage('admin')}>admin</button>}<button onClick={()=>{clearToken();setUser(null)}}>logout</button></nav><main className="container"><Stats user={user}/>{page==='dashboard'&&<Dashboard/>}{page==='jobs'&&<Jobs refresh={refresh}/>} {page==='recruitment'&&<Recruitment refresh={refresh}/>} {page==='my gang'&&<MyGang refresh={refresh}/>} {page==='crimes'&&<Crimes refresh={refresh}/>} {page==='weapons'&&<Weapons refresh={refresh}/>} {page==='inventory'&&<Inventory/>}{page==='market'&&<DrugMarket/>}{page==='gangs'&&<Gangs/>}{page==='territories'&&<Territories/>}{page==='admin'&&<Admin/>}</main></div>
}
function Auth({onLogin,error,setError}:{onLogin:(u:User)=>void;error:string;setError:(e:string)=>void}){const [mode,setMode]=useState<'login'|'register'>('login'); const [form,setForm]=useState({username:'',email:'admin@criminal.test',password:'password'}); async function submit(){try{setError(''); const r=await api<{token:string;user:User}>(mode==='login'?'/login':'/register',{method:'POST',body:JSON.stringify(form)}); setToken(r.token); onLogin(r.user);}catch(e:any){setError(e.message)}} return <div className="container"><div className="card" style={{maxWidth:420,margin:'8vh auto'}}><h1>Criminal Empire Online</h1><p className="muted">v0.1 MVP</p>{mode==='register'&&<input placeholder="username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/>}<input placeholder="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<p className="danger">{error}</p>}<button className="btn primary" onClick={submit}>{mode}</button><button className="btn" onClick={()=>setMode(mode==='login'?'register':'login')}>switch to {mode==='login'?'register':'login'}</button></div></div>}
function Stats({user}:{user:User}){return <div className="grid"><div className="card"><div className="muted">Cash</div><div className="stat">${user.cash.toLocaleString()}</div></div><div className="card"><div className="muted">Energy</div><div className="stat">{user.energy}/{user.max_energy}</div></div><div className="card"><div className="muted">Heat</div><div className="stat danger">{user.heat}</div></div><div className="card"><div className="muted">Level / XP</div><div className="stat">{user.level} / {user.experience}</div></div></div>}
function Dashboard(){return <div className="card"><h2>Street-Level Beginning</h2><p>You begin alone with $500. Work small NPC jobs, build reputation, recruit your first crew member, and slowly create a criminal organization inside a simulated city.</p></div>}

function Jobs({refresh}:{refresh:()=>void}){const [items,setItems]=useState<any[]>([]);const [active,setActive]=useState<any[]>([]);const [members,setMembers]=useState<any[]>([]);const [selected,setSelected]=useState<number[]>([]);const [msg,setMsg]=useState('');async function load(){const [a,b,c]=await Promise.all([api<any>('/jobs'),api<any>('/jobs/active'),api<any>('/my-gang')]);setItems(a.data);setActive(b.data);setMembers(c.data)}useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);async function start(id:number){try{const r=await api<any>(`/jobs/${id}/start`,{method:'POST',body:JSON.stringify({member_ids:selected,idempotency_key:crypto.randomUUID()})});setMsg(r.message);setSelected([]);refresh();load()}catch(e:any){setMsg(e.message)}}async function complete(id:number){try{const r=await api<any>(`/job-runs/${id}/complete`,{method:'POST'});setMsg(r.success?`Success: earned $${r.reward}`:`Failed. Heat +${r.heat_gained}`);refresh();load()}catch(e:any){setMsg(e.message)}}return <><h2>NPC Jobs</h2>{msg&&<div className="card">{msg}</div>}{active.length>0&&<div className="card"><h3>Active jobs</h3>{active.map(x=><div key={x.id} className="row"><strong>{x.name}</strong><span>{Math.max(0,Number(x.seconds_remaining))} seconds remaining</span><button className="btn primary" disabled={Number(x.seconds_remaining)>0} onClick={()=>complete(x.id)}>Complete</button></div>)}</div>}<div className="card"><h3>Assign crew (optional)</h3>{members.filter(m=>m.status==='active').map(m=><label key={m.id} style={{marginRight:12}}><input style={{width:'auto'}} type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(e.target.checked?[...selected,m.id]:selected.filter(id=>id!==m.id))}/>{m.nickname||m.first_name}</label>)}</div><div className="grid">{items.map(j=><div className="card" key={j.opportunity_id}><h3>{j.name}</h3><p className="muted">{j.description}</p><p>From: {j.giver_nickname||`${j.giver_first_name||''} ${j.giver_last_name||''}`} · {j.territory_name}</p><p>${j.reward_min}–${j.reward_max} · {j.duration_seconds_effective}s · energy {j.energy_cost}</p><p>Risk: difficulty {j.difficulty} · expected heat {j.heat_min}–{j.heat_max}</p><button className="btn primary" disabled={!j.can_start} onClick={()=>start(j.opportunity_id)}>Start</button>{!j.can_start&&<p className="danger">Requirements not met</p>}</div>)}</div></>}
function Recruitment({refresh}:{refresh:()=>void}){const [items,setItems]=useState<any[]>([]);const [msg,setMsg]=useState('');async function load(){setItems((await api<any>('/recruitment')).data)}useEffect(()=>{load()},[]);async function hire(id:number){if(!confirm('Hire this NPC? Recruitment fees are not refundable.'))return;try{const r=await api<any>(`/recruitment/${id}/hire`,{method:'POST'});setMsg(r.message);refresh();load()}catch(e:any){setMsg(e.message)}}return <><h2>Recruitment</h2>{msg&&<div className="card">{msg}</div>}<div className="grid">{items.map(x=><div className="card" key={x.id}><h3>{x.first_name} “{x.nickname}” {x.last_name}</h3><p>{x.age} · {x.occupation} · {x.territory_name}</p><p className="muted">{x.biography}</p><p>Fee ${x.recruitment_fee} · salary ${x.salary_weekly}/week · personal cash ${x.personal_cash}</p><p>STR {x.strength} · DRV {x.driving} · INT {x.intelligence} · STL {x.stealth} · INTIM {x.intimidation}</p><p>{x.traits.map((t:any)=>t.name).join(', ')||'No notable traits'}</p><button className="btn primary" disabled={!x.can_hire} onClick={()=>hire(x.id)}>Hire</button></div>)}</div></>}
function MyGang({refresh}:{refresh:()=>void}){const [items,setItems]=useState<any[]>([]);const [msg,setMsg]=useState('');async function load(){setItems((await api<any>('/my-gang')).data)}useEffect(()=>{load()},[]);async function pay(id:number){try{const r=await api<any>(`/my-gang/${id}/pay-overdue`,{method:'POST'});setMsg(`${r.message}: $${r.amount}`);refresh();load()}catch(e:any){setMsg(e.message)}}return <><h2>My Gang</h2>{msg&&<div className="card">{msg}</div>}{items.length===0&&<div className="card">You are still alone. Complete beginner jobs and hire your first recruit.</div>}<div className="grid">{items.map(m=><div className="card" key={m.id}><h3>{m.first_name} “{m.nickname}” {m.last_name}</h3><p>{m.age} · {m.occupation} · {m.territory_name}</p><p className="muted">{m.biography}</p><p>Status {m.status} · Health {m.health}/{m.max_health} · Morale {m.morale} · Loyalty {m.loyalty}</p><p>Personal cash ${m.personal_cash} · salary ${m.salary_weekly}/week · unpaid ${m.unpaid_salary}</p><p>Level {m.level} · XP {m.experience}</p><p>STR {m.strength} · SHO {m.shooting} · DRV {m.driving} · INT {m.intelligence} · STL {m.stealth}</p><p>Traits: {m.traits.map((t:any)=>t.name).join(', ')||'none'}</p>{Number(m.unpaid_salary)>0&&<button className="btn primary" onClick={()=>pay(m.id)}>Pay overdue salary</button>}</div>)}</div></>}

function Crimes({refresh}:{refresh:()=>void}){const [items,setItems]=useState<Crime[]>([]);const [msg,setMsg]=useState('');useEffect(()=>{api<{data:Crime[]}>('/crimes').then(r=>setItems(r.data))},[]);async function commit(id:number){try{const r=await api<any>(`/crimes/${id}/commit`,{method:'POST'});setMsg(r.success?`Success! Earned $${r.reward}`:`Failed. Heat +${r.heat_gained}`);refresh()}catch(e:any){setMsg(e.message)}}return <><h2>Crimes</h2>{msg&&<div className="card">{msg}</div>}<div className="grid">{items.map(c=><div className="card" key={c.id}><h3>{c.name}</h3><p className="muted">{c.description}</p><p>Energy: {c.energy_cost} | Success: {c.success_rate}% | Heat: +{c.heat_gain}</p><p>Reward: ${c.reward_min} - ${c.reward_max}</p><button className="btn primary" onClick={()=>commit(c.id)}>Commit</button></div>)}</div></>}
function Weapons({refresh}:{refresh:()=>void}){const [items,setItems]=useState<Weapon[]>([]);const [msg,setMsg]=useState('');useEffect(()=>{api<{data:Weapon[]}>('/weapons').then(r=>setItems(r.data))},[]);async function buy(id:number){try{const r=await api<any>(`/weapons/${id}/buy`,{method:'POST'});setMsg(r.message);refresh()}catch(e:any){setMsg(e.message)}}return <><h2>Weapon Shop</h2>{msg&&<div className="card">{msg}</div>}<div className="grid">{items.map(w=><div className="card" key={w.id}><h3>{w.name}</h3><p>{w.class}</p><p>Damage {w.damage} | Accuracy {w.accuracy} | Concealment {w.concealment}</p><p>${w.price.toLocaleString()}</p><button className="btn primary" onClick={()=>buy(w.id)}>Buy</button></div>)}</div></>}
function Inventory(){const [data,setData]=useState<any>({weapons:[],drugs:[]});useEffect(()=>{api<any>('/inventory').then(setData)},[]);return <div className="grid"><div className="card"><h2>Weapons</h2>{data.weapons.map((x:any)=><p key={x.id}>{x.name} × {x.quantity}</p>)}</div><div className="card"><h2>Drugs</h2>{data.drugs.map((x:any)=><p key={x.id}>{x.name} × {x.quantity}</p>)}</div></div>}
function DrugMarket(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{api<any>('/drug-market').then(r=>setItems(r.data))},[]);return <div className="card"><h2>Drug Market</h2><table className="table"><tbody>{items.map((d,i)=><tr key={i}><td>{d.region}</td><td>{d.name}</td><td>${Number(d.price).toLocaleString()}</td><td>Supply {d.supply}</td><td>Demand {d.demand}</td><td>Police {d.police_pressure}</td></tr>)}</tbody></table></div>}
function Gangs(){const [items,setItems]=useState<any[]>([]); const [name,setName]=useState(''); async function load(){const r=await api<any>('/gangs');setItems(r.data)} useEffect(()=>{load()},[]); async function create(){await api('/gangs',{method:'POST',body:JSON.stringify({name})});setName('');load()} return <div className="card"><h2>Gangs</h2><div className="row"><input placeholder="Gang name" value={name} onChange={e=>setName(e.target.value)}/><button className="btn primary" onClick={create}>Create</button></div>{items.map(g=><p key={g.id}>{g.name} — reputation {g.reputation} — treasury ${g.treasury}</p>)}</div>}
function Territories(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{api<any>('/territories').then(r=>setItems(r.data))},[]);return <div className="grid">{items.map(t=><div className="card" key={t.id}><h3>{t.name}</h3><p>Population {Number(t.population).toLocaleString()}</p><p>Wealth {t.wealth} | Crime {t.crime_rate} | Govt {t.government_presence}</p><p>Owner: {t.owner_gang || 'Uncontrolled'}</p></div>)}</div>}
function Admin(){const [stats,setStats]=useState<any>(null);const [logs,setLogs]=useState<any[]>([]);useEffect(()=>{api<any>('/admin/dashboard').then(r=>setStats(r.stats));api<any>('/admin/audit').then(r=>setLogs(r.data))},[]);return <div className="card"><h2>Admin</h2><pre>{JSON.stringify(stats,null,2)}</pre><h3>Audit</h3>{logs.map(l=><p key={l.id}>{l.created_at} — {l.action}</p>)}</div>}

createRoot(document.getElementById('root')!).render(<App/>);
